# change the version numer to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.17.3

source:
  path: ../..
  patches:
    - fix_graphicshr_location.patch [win]

build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - patch             [win]
    - python
    - oce ==0.17.3
    - cmake
    - ninja
    - swig
    - freetype
    - gcc               [linux]

  run:
    - pyqt >=5
    - oce ==0.17.3
    - python
    - freetype
    - pyobjc-core       [osx and py27]

test:
  requires:
    - scipy
    - wxpython          [py27]
    - pyside            [py27]

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
