{% set version = "7.4.0" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  path: ../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - cmake
    - swig >=3.0.11

  host:
    - python {{ python }}
    - opencascade ==7.4.0

  run:
    - opencascade ==7.4.0
    - python

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
  requires:
    - pyqt >=5
    - mypy
    - svgwrite

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
