package:
  name: pythonocc-core
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.16.4') }}

source:
  path: ../..
  patches:
    - fix_graphicshr_location.patch [win]

build:

build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - patch             [win]
    - python
    - oce ==0.17.1
    - cmake
    - swig

  run:
    - pyqt
    - wxpython          [py27]
    - pyside            [py27]
    - oce ==0.17.1
    - python


about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library
