# change the version number to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.18

source:
  path: ../..


build:
  script_env:
    - CC
    - CXX

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  binary_relocation: false [osx]
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python
    - oce ==0.18.1
    - cmake ==3.8.0
    - ninja ==1.7.2
    - swig ==3.0.11
    - freetype ==2.7
    - smesh ==6.7.4

  run:
    - pyqt >=5
    - oce ==0.18.1
    - python
    - freetype ==2.7
    - smesh ==6.7.4

test:
  requires:
    - scipy
    - wxpython          [py27]
    - pyside            [py27]
    - smesh ==6.7.4

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
