{% set version = "7.9.3" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  path: ../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - ninja
    - cmake
    - swig ==4.4.1

  host:
    - python {{ python }}
    - python_abi * *_cp313  [py==313]
    - occt ==7.9.3
    - numpy >=1.17

  run:
    - occt ==7.9.3
    - numpy >=1.17
    - python_abi * *_cp313  [py==313]

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
    - OCC.Core.Tesselator
  requires:
    - pyqt5-sip       # [win]
    - pyside6 >=6.10  # [win]
    - wxpython >=4.2  # [win]
    - svgwrite >=1.4
    - mypy
    - pytest

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: Python package for 3D geometry CAD/BIM/CAM
