{% set version = "7.9.0" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  path: ../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - ninja
    - cmake
    - swig ==4.2.1

  host:
    - python {{ python }}
    - occt ==7.9.0
    - numpy >=1.17

  run:
    - occt ==7.9.0
    - numpy >=1.17

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
    - OCC.Core.Tesselator
  requires:
    - pyqt >=5
    - mypy
    - pytest
    - svgwrite
    - wxpython >=4
    - pyside6

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: Python package for 3D geometry CAD/BIM/CAM
