# change the version number to "0.17.1" or "0.18" in case of a release build
package:
  name: pythonocc-core
  version: 0.18.2

source:
  path: ../..


build:
  script_env:
    - CC
    - CXX

  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - tbb
    - cmake
    - ninja
    - swig >=3.0.11
    - freetype ==2.9.1

  host:
    - python {{ python }}
    - oce ==0.18.3
    - smesh ==6.7.6

  run:
    - oce ==0.18.3
    - python {{ python }}
    - tbb >=2018_20171205
    - freetype >=2.7
    - smesh ==6.7.6
    - pyqt >=5

test:
  requires:
    - numpy
    - pyqt >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
