{% set version = "7.6.3" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  path: ../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - ninja
    - cmake
    - swig ==4.0.2

  host:
    - python {{ python }}
    - occt ==7.6.3
    - numpy >=1.17

  run:
    - occt ==7.6.3
    - six
    - numpy >=1.17

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
    - OCC.Core.MeshDS
    - OCC.Core.Tesselator
  requires:
    - pyqt >=5
    - mypy
    - svgwrite
    - wxpython >=4
    - pyside2 >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package
