package:
  name: pythonocc-core
  version: 0.16.0-dev

source:
    git_url: https://github.com/jf---/pythonocc-core.git
    sha1: 55f9128c0247da27beefaa3e3ec32a8ba2dedb5c

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - python
    - opencascade_community_edition
    - swig 2.0.10

  run:
    - python
    - opencascade_community_edition

#test:
#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - nosetests test/run_tests.py
#
#
#  # You can also put a file called run_test.py in the recipe that will be run
#  # at test time.
#
#  requires:
#    # Put any additional test requirements here.  For example
#    - nose

about:
  home: https://github.com/tpaviot/pythonocc-core
  summary: https://github.com/tpaviot/pythonocc-core/blob/master/README.md
  license: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
