from OCC.Core.AIS import AIS_Shape
from OCC.Core.gp import gp_Trsf
from OCC.Core.Graphic3d import Graphic3d_NameOfMaterial
from OCC.Core.TopoDS import TopoDS_Shape
from OCC.Display.OCCViewer import Viewer3d

class Layer:
    color: int
    display: Viewer3d
    transparency: float
    material: Graphic3d_NameOfMaterial
    element_to_display: dict[int, tuple[TopoDS_Shape, AIS_Shape]]
    count: int

    def __init__(
        self,
        from_display: Viewer3d,
        shape: TopoDS_Shape | None = None,
        color: int = 0,
        transparency: float = 0.0,
        material: Graphic3d_NameOfMaterial = ...,
    ) -> None: ...
    def add_shape(self, shape: TopoDS_Shape) -> None: ...
    def replace_shape(self, shape: TopoDS_Shape, index: int) -> None: ...
    def update_trsf_shape(
        self, shape: TopoDS_Shape, index: int, transformations: gp_Trsf
    ) -> None: ...
    def merge(self, layer: Layer, clear: bool = False) -> None: ...
    def delete_shape_with_index(self, index: int) -> None: ...
    def delete_shape(self, shape_to_del: TopoDS_Shape) -> None: ...
    def clear(self) -> None: ...
    def get_shapes(self) -> list[TopoDS_Shape]: ...
    def get_aisshape_from_topodsshape(
        self, topshape: TopoDS_Shape
    ) -> tuple[AIS_Shape, int] | None: ...
    def hide(self) -> None: ...
    def show(self) -> None: ...
