def assert_shape_not_null(shp) -> None: ...
def assert_isdone(inst, message) -> None: ...
def point_list_to_TColgp_Array1OfPnt(li): ...
def make_vertex(*args): ...
def make_edge(*args): ...
def make_edge2d(*args): ...
def make_wire(*args): ...
def points_to_bspline(pnts): ...
def edge_to_bezier(topods_edge): ...
def make_n_sided(edges, continuity=...): ...
def make_face(*args): ...
def get_aligned_boundingbox(shape, tol: float = 1e-06, optimal_BB: bool = True): ...
def get_oriented_boundingbox(shape, optimal_OBB: bool = True): ...
def midpoint(point_A, point_B): ...
def center_boundingbox(shape): ...
def get_boundingbox(shape, tol: float = 1e-06, use_mesh: bool = True): ...
def translate_shp(shp, vec, copy: bool = False): ...
def rotate_shape(shape, axis, angle, unite: str = "deg"): ...
def rotate_shp_3_axis(shape, rx, ry, rz, unity: str = "deg"): ...
def scale_shape(shape, fx, fy, fz): ...
def make_extrusion(face, length, vector=None): ...
def recognize_face(topods_face): ...
def measure_shape_volume(shape): ...
def measure_shape_mass_center_of_gravity(shape): ...
