import tkinter as tk
from typing import Any

from OCC.Display.OCCViewer import Viewer3d

ZOOM_STEP: float

class tkViewer3d(tk.Frame):
    def __init__(self, parent: Any, width: int = 1024, height: int = 768) -> None: ...
    @property
    def display(self) -> Viewer3d: ...
    def LeftDown(self, event: Any) -> None: ...
    def Rotate(self, event: Any) -> None: ...
    def Pan(self, event: Any) -> None: ...
    def Zoom(self, event: Any) -> None: ...
    def Resize(self, event: Any) -> None: ...
    def Map(self, event: Any) -> None: ...
