from enum import IntEnum
from typing import overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.Adaptor2d import *
from OCC.Core.Geom2d import *
from OCC.Core.gp import *
from OCC.Core.GeomAbs import *
from OCC.Core.Adaptor3d import *
from OCC.Core.Geom import *
from OCC.Core.GeomAdaptor import *
from OCC.Core.math import *

# the following typedef cannot be wrapped as is
Extrema_Array2OfPOnCurv = NewType("Extrema_Array2OfPOnCurv", Any)
# the following typedef cannot be wrapped as is
Extrema_Array2OfPOnCurv2d = NewType("Extrema_Array2OfPOnCurv2d", Any)
# the following typedef cannot be wrapped as is
Extrema_Array2OfPOnSurf = NewType("Extrema_Array2OfPOnSurf", Any)
# the following typedef cannot be wrapped as is
Extrema_Array2OfPOnSurfParams = NewType("Extrema_Array2OfPOnSurfParams", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray1OfPOnCurv = NewType("Extrema_HArray1OfPOnCurv", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray1OfPOnCurv2d = NewType("Extrema_HArray1OfPOnCurv2d", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray1OfPOnSurf = NewType("Extrema_HArray1OfPOnSurf", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray2OfPOnCurv = NewType("Extrema_HArray2OfPOnCurv", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray2OfPOnCurv2d = NewType("Extrema_HArray2OfPOnCurv2d", Any)
# the following typedef cannot be wrapped as is
Extrema_HArray2OfPOnSurf = NewType("Extrema_HArray2OfPOnSurf", Any)
# the following typedef cannot be wrapped as is
Extrema_HUBTreeOfSphere = NewType("Extrema_HUBTreeOfSphere", Any)
# the following typedef cannot be wrapped as is
Extrema_UBTreeFillerOfSphere = NewType("Extrema_UBTreeFillerOfSphere", Any)
# the following typedef cannot be wrapped as is
Extrema_UBTreeOfSphere = NewType("Extrema_UBTreeOfSphere", Any)

class Extrema_Array1OfPOnCurv:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def __getitem__(self, index: int) -> Extrema_POnCurv: ...
    def __setitem__(self, index: int, value: Extrema_POnCurv) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Extrema_POnCurv]: ...
    def next(self) -> Extrema_POnCurv: ...
    __next__ = next
    def Init(self, theValue: Extrema_POnCurv) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDetectable(self) -> bool: ...
    def IsAllocated(self) -> bool: ...
    def First(self) -> Extrema_POnCurv: ...
    def Last(self) -> Extrema_POnCurv: ...
    def Value(self, theIndex: int) -> Extrema_POnCurv: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnCurv) -> None: ...

class Extrema_Array1OfPOnCurv2d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def __getitem__(self, index: int) -> Extrema_POnCurv2d: ...
    def __setitem__(self, index: int, value: Extrema_POnCurv2d) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Extrema_POnCurv2d]: ...
    def next(self) -> Extrema_POnCurv2d: ...
    __next__ = next
    def Init(self, theValue: Extrema_POnCurv2d) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDetectable(self) -> bool: ...
    def IsAllocated(self) -> bool: ...
    def First(self) -> Extrema_POnCurv2d: ...
    def Last(self) -> Extrema_POnCurv2d: ...
    def Value(self, theIndex: int) -> Extrema_POnCurv2d: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnCurv2d) -> None: ...

class Extrema_Array1OfPOnSurf:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def __getitem__(self, index: int) -> Extrema_POnSurf: ...
    def __setitem__(self, index: int, value: Extrema_POnSurf) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Extrema_POnSurf]: ...
    def next(self) -> Extrema_POnSurf: ...
    __next__ = next
    def Init(self, theValue: Extrema_POnSurf) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDetectable(self) -> bool: ...
    def IsAllocated(self) -> bool: ...
    def First(self) -> Extrema_POnSurf: ...
    def Last(self) -> Extrema_POnSurf: ...
    def Value(self, theIndex: int) -> Extrema_POnSurf: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnSurf) -> None: ...

class Extrema_SequenceOfPOnCurv:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def First(self) -> Extrema_POnCurv: ...
    def Last(self) -> Extrema_POnCurv: ...
    def Length(self) -> int: ...
    def Append(self, theItem: Extrema_POnCurv) -> Extrema_POnCurv: ...
    def Prepend(self, theItem: Extrema_POnCurv) -> Extrema_POnCurv: ...
    def RemoveFirst(self) -> None: ...
    def Reverse(self) -> None: ...
    def Value(self, theIndex: int) -> Extrema_POnCurv: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnCurv) -> None: ...

class Extrema_SequenceOfPOnCurv2d:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def First(self) -> Extrema_POnCurv2d: ...
    def Last(self) -> Extrema_POnCurv2d: ...
    def Length(self) -> int: ...
    def Append(self, theItem: Extrema_POnCurv2d) -> Extrema_POnCurv2d: ...
    def Prepend(self, theItem: Extrema_POnCurv2d) -> Extrema_POnCurv2d: ...
    def RemoveFirst(self) -> None: ...
    def Reverse(self) -> None: ...
    def Value(self, theIndex: int) -> Extrema_POnCurv2d: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnCurv2d) -> None: ...

class Extrema_SequenceOfPOnSurf:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def First(self) -> Extrema_POnSurf: ...
    def Last(self) -> Extrema_POnSurf: ...
    def Length(self) -> int: ...
    def Append(self, theItem: Extrema_POnSurf) -> Extrema_POnSurf: ...
    def Prepend(self, theItem: Extrema_POnSurf) -> Extrema_POnSurf: ...
    def RemoveFirst(self) -> None: ...
    def Reverse(self) -> None: ...
    def Value(self, theIndex: int) -> Extrema_POnSurf: ...
    def SetValue(self, theIndex: int, theValue: Extrema_POnSurf) -> None: ...

class Extrema_ElementType(IntEnum):
    Extrema_Node: int = ...
    Extrema_UIsoEdge: int = ...
    Extrema_VIsoEdge: int = ...
    Extrema_Face: int = ...

Extrema_Node = Extrema_ElementType.Extrema_Node
Extrema_UIsoEdge = Extrema_ElementType.Extrema_UIsoEdge
Extrema_VIsoEdge = Extrema_ElementType.Extrema_VIsoEdge
Extrema_Face = Extrema_ElementType.Extrema_Face

class Extrema_ExtAlgo(IntEnum):
    Extrema_ExtAlgo_Grad: int = ...
    Extrema_ExtAlgo_Tree: int = ...

Extrema_ExtAlgo_Grad = Extrema_ExtAlgo.Extrema_ExtAlgo_Grad
Extrema_ExtAlgo_Tree = Extrema_ExtAlgo.Extrema_ExtAlgo_Tree

class Extrema_ExtFlag(IntEnum):
    Extrema_ExtFlag_MIN: int = ...
    Extrema_ExtFlag_MAX: int = ...
    Extrema_ExtFlag_MINMAX: int = ...

Extrema_ExtFlag_MIN = Extrema_ExtFlag.Extrema_ExtFlag_MIN
Extrema_ExtFlag_MAX = Extrema_ExtFlag.Extrema_ExtFlag_MAX
Extrema_ExtFlag_MINMAX = Extrema_ExtFlag.Extrema_ExtFlag_MINMAX

class Extrema_Curve2dTool:
    @staticmethod
    def BSpline(theC: Adaptor2d_Curve2d) -> Geom2d_BSplineCurve: ...
    @staticmethod
    def Bezier(theC: Adaptor2d_Curve2d) -> Geom2d_BezierCurve: ...
    @staticmethod
    def Circle(theC: Adaptor2d_Curve2d) -> gp_Circ2d: ...
    @staticmethod
    def Continuity(theC: Adaptor2d_Curve2d) -> GeomAbs_Shape: ...
    @staticmethod
    def D0(theC: Adaptor2d_Curve2d, theU: float, theP: gp_Pnt2d) -> None: ...
    @staticmethod
    def D1(theC: Adaptor2d_Curve2d, theU: float, theP: gp_Pnt2d, theV: gp_Vec2d) -> None: ...
    @staticmethod
    def D2(theC: Adaptor2d_Curve2d, theU: float, theP: gp_Pnt2d, theV1: gp_Vec2d, theV2: gp_Vec2d) -> None: ...
    @staticmethod
    def D3(theC: Adaptor2d_Curve2d, theU: float, theP: gp_Pnt2d, theV1: gp_Vec2d, theV2: gp_Vec2d, theV3: gp_Vec2d) -> None: ...
    @staticmethod
    def DN(theC: Adaptor2d_Curve2d, theU: float, theN: int) -> gp_Vec2d: ...
    @staticmethod
    def DeflCurvIntervals(theC: Adaptor2d_Curve2d) -> False: ...
    @staticmethod
    def Degree(theC: Adaptor2d_Curve2d) -> int: ...
    @staticmethod
    def Ellipse(theC: Adaptor2d_Curve2d) -> gp_Elips2d: ...
    @staticmethod
    def FirstParameter(theC: Adaptor2d_Curve2d) -> False: ...
    @staticmethod
    def GetType(theC: Adaptor2d_Curve2d) -> GeomAbs_CurveType: ...
    @staticmethod
    def Hyperbola(theC: Adaptor2d_Curve2d) -> gp_Hypr2d: ...
    @staticmethod
    def IsClosed(theC: Adaptor2d_Curve2d) -> bool: ...
    @staticmethod
    def IsPeriodic(theC: Adaptor2d_Curve2d) -> bool: ...
    @staticmethod
    def IsRational(theC: Adaptor2d_Curve2d) -> bool: ...
    @staticmethod
    def LastParameter(theC: Adaptor2d_Curve2d) -> False: ...
    @staticmethod
    def Line(theC: Adaptor2d_Curve2d) -> gp_Lin2d: ...
    @staticmethod
    def NbIntervals(theC: Adaptor2d_Curve2d, theS: GeomAbs_Shape) -> int: ...
    @staticmethod
    def NbKnots(theC: Adaptor2d_Curve2d) -> int: ...
    @staticmethod
    def NbPoles(theC: Adaptor2d_Curve2d) -> int: ...
    @staticmethod
    def Parabola(theC: Adaptor2d_Curve2d) -> gp_Parab2d: ...
    @staticmethod
    def Period(theC: Adaptor2d_Curve2d) -> False: ...
    @staticmethod
    def Resolution(theC: Adaptor2d_Curve2d, theR3d: float) -> False: ...
    @staticmethod
    def Value(theC: Adaptor2d_Curve2d, theU: float) -> gp_Pnt2d: ...

class Extrema_CurveTool:
    @staticmethod
    def BSpline(theC: Adaptor3d_Curve) -> Geom_BSplineCurve: ...
    @staticmethod
    def Bezier(theC: Adaptor3d_Curve) -> Geom_BezierCurve: ...
    @staticmethod
    def Circle(theC: Adaptor3d_Curve) -> gp_Circ: ...
    @staticmethod
    def Continuity(theC: Adaptor3d_Curve) -> GeomAbs_Shape: ...
    @staticmethod
    def D0(theC: Adaptor3d_Curve, theU: float, theP: gp_Pnt) -> None: ...
    @staticmethod
    def D1(theC: Adaptor3d_Curve, theU: float, theP: gp_Pnt, theV: gp_Vec) -> None: ...
    @staticmethod
    def D2(theC: Adaptor3d_Curve, theU: float, theP: gp_Pnt, theV1: gp_Vec, theV2: gp_Vec) -> None: ...
    @staticmethod
    def D3(theC: Adaptor3d_Curve, theU: float, theP: gp_Pnt, theV1: gp_Vec, theV2: gp_Vec, theV3: gp_Vec) -> None: ...
    @staticmethod
    def DN(theC: Adaptor3d_Curve, theU: float, theN: int) -> gp_Vec: ...
    @staticmethod
    def DeflCurvIntervals(theC: Adaptor3d_Curve) -> False: ...
    @staticmethod
    def Degree(theC: Adaptor3d_Curve) -> int: ...
    @staticmethod
    def Ellipse(theC: Adaptor3d_Curve) -> gp_Elips: ...
    @staticmethod
    def FirstParameter(theC: Adaptor3d_Curve) -> False: ...
    @staticmethod
    def GetType(theC: Adaptor3d_Curve) -> GeomAbs_CurveType: ...
    @staticmethod
    def Hyperbola(theC: Adaptor3d_Curve) -> gp_Hypr: ...
    @staticmethod
    def IsPeriodic(theC: Adaptor3d_Curve) -> bool: ...
    @staticmethod
    def IsRational(theC: Adaptor3d_Curve) -> bool: ...
    @staticmethod
    def LastParameter(theC: Adaptor3d_Curve) -> False: ...
    @staticmethod
    def Line(theC: Adaptor3d_Curve) -> gp_Lin: ...
    @staticmethod
    def NbIntervals(theC: Adaptor3d_Curve, theS: GeomAbs_Shape) -> int: ...
    @staticmethod
    def NbKnots(theC: Adaptor3d_Curve) -> int: ...
    @staticmethod
    def NbPoles(theC: Adaptor3d_Curve) -> int: ...
    @staticmethod
    def Parabola(theC: Adaptor3d_Curve) -> gp_Parab: ...
    @staticmethod
    def Period(theC: Adaptor3d_Curve) -> False: ...
    @staticmethod
    def Resolution(theC: Adaptor3d_Curve, theR3d: float) -> False: ...
    @staticmethod
    def Value(theC: Adaptor3d_Curve, theU: float) -> gp_Pnt: ...

class Extrema_ExtCC:
    @overload
    def __init__(self, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    @overload
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    @overload
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve, U1: float, U2: float, V1: float, V2: float, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    def GetSingleSolutionFlag(self) -> bool: ...
    @overload
    def Initialize(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    @overload
    def Initialize(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve, U1: float, U2: float, V1: float, V2: float, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self) -> None: ...
    def Points(self, N: int, P1: Extrema_POnCurv, P2: Extrema_POnCurv) -> None: ...
    @overload
    def SetCurve(self, theRank: int, C: Adaptor3d_Curve) -> None: ...
    @overload
    def SetCurve(self, theRank: int, C: Adaptor3d_Curve, Uinf: float, Usup: float) -> None: ...
    def SetRange(self, theRank: int, Uinf: float, Usup: float) -> None: ...
    def SetSingleSolutionFlag(self, theSingleSolutionFlag: bool) -> None: ...
    def SetTolerance(self, theRank: int, Tol: float) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtCC2d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    @overload
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d, U1: float, U2: float, V1: float, V2: float, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    def GetSingleSolutionFlag(self) -> bool: ...
    def Initialize(self, C2: Adaptor2d_Curve2d, V1: float, V2: float, TolC1: Optional[float] = 1.0e-10, TolC2: Optional[float] = 1.0e-10) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, C1: Adaptor2d_Curve2d, U1: float, U2: float) -> None: ...
    def Points(self, N: int, P1: Extrema_POnCurv2d, P2: Extrema_POnCurv2d) -> None: ...
    def SetSingleSolutionFlag(self, theSingleSolutionFlag: bool) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtCS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, TolC: float, TolS: float) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, UCinf: float, UCsup: float, Uinf: float, Usup: float, Vinf: float, Vsup: float, TolC: float, TolS: float) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, TolC: float, TolS: float) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, Uinf: float, Usup: float, Vinf: float, Vsup: float, TolC: float, TolS: float) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, C: Adaptor3d_Curve, Uinf: float, Usup: float) -> None: ...
    def Points(self, N: int, P1: Extrema_POnCurv, P2: Extrema_POnSurf) -> None: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtElC:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin, C2: gp_Lin, AngTol: float) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin, C2: gp_Circ, Tol: float) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin, C2: gp_Elips) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin, C2: gp_Hypr) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin, C2: gp_Parab) -> None: ...
    @overload
    def __init__(self, C1: gp_Circ, C2: gp_Circ) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Points(self, N: int, P1: Extrema_POnCurv, P2: Extrema_POnCurv) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtElC2d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin2d, C2: gp_Lin2d, AngTol: float) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin2d, C2: gp_Circ2d, Tol: float) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin2d, C2: gp_Elips2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin2d, C2: gp_Hypr2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Lin2d, C2: gp_Parab2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Circ2d, C2: gp_Circ2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Circ2d, C2: gp_Elips2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Circ2d, C2: gp_Hypr2d) -> None: ...
    @overload
    def __init__(self, C1: gp_Circ2d, C2: gp_Parab2d) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Points(self, N: int, P1: Extrema_POnCurv2d, P2: Extrema_POnCurv2d) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtElCS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C: gp_Lin, S: gp_Pln) -> None: ...
    @overload
    def __init__(self, C: gp_Lin, S: gp_Cylinder) -> None: ...
    @overload
    def __init__(self, C: gp_Lin, S: gp_Cone) -> None: ...
    @overload
    def __init__(self, C: gp_Lin, S: gp_Sphere) -> None: ...
    @overload
    def __init__(self, C: gp_Lin, S: gp_Torus) -> None: ...
    @overload
    def __init__(self, C: gp_Circ, S: gp_Pln) -> None: ...
    @overload
    def __init__(self, C: gp_Circ, S: gp_Cylinder) -> None: ...
    @overload
    def __init__(self, C: gp_Circ, S: gp_Cone) -> None: ...
    @overload
    def __init__(self, C: gp_Circ, S: gp_Sphere) -> None: ...
    @overload
    def __init__(self, C: gp_Circ, S: gp_Torus) -> None: ...
    @overload
    def __init__(self, C: gp_Hypr, S: gp_Pln) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, C: gp_Lin, S: gp_Pln) -> None: ...
    @overload
    def Perform(self, C: gp_Lin, S: gp_Cylinder) -> None: ...
    @overload
    def Perform(self, C: gp_Lin, S: gp_Cone) -> None: ...
    @overload
    def Perform(self, C: gp_Lin, S: gp_Sphere) -> None: ...
    @overload
    def Perform(self, C: gp_Lin, S: gp_Torus) -> None: ...
    @overload
    def Perform(self, C: gp_Circ, S: gp_Pln) -> None: ...
    @overload
    def Perform(self, C: gp_Circ, S: gp_Cylinder) -> None: ...
    @overload
    def Perform(self, C: gp_Circ, S: gp_Cone) -> None: ...
    @overload
    def Perform(self, C: gp_Circ, S: gp_Sphere) -> None: ...
    @overload
    def Perform(self, C: gp_Circ, S: gp_Torus) -> None: ...
    @overload
    def Perform(self, C: gp_Hypr, S: gp_Pln) -> None: ...
    def Points(self, N: int, P1: Extrema_POnCurv, P2: Extrema_POnSurf) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtElSS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, S1: gp_Pln, S2: gp_Pln) -> None: ...
    @overload
    def __init__(self, S1: gp_Pln, S2: gp_Sphere) -> None: ...
    @overload
    def __init__(self, S1: gp_Sphere, S2: gp_Sphere) -> None: ...
    @overload
    def __init__(self, S1: gp_Sphere, S2: gp_Cylinder) -> None: ...
    @overload
    def __init__(self, S1: gp_Sphere, S2: gp_Cone) -> None: ...
    @overload
    def __init__(self, S1: gp_Sphere, S2: gp_Torus) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, S1: gp_Pln, S2: gp_Pln) -> None: ...
    @overload
    def Perform(self, S1: gp_Pln, S2: gp_Sphere) -> None: ...
    @overload
    def Perform(self, S1: gp_Sphere, S2: gp_Sphere) -> None: ...
    @overload
    def Perform(self, S1: gp_Sphere, S2: gp_Cylinder) -> None: ...
    @overload
    def Perform(self, S1: gp_Sphere, S2: gp_Cone) -> None: ...
    @overload
    def Perform(self, S1: gp_Sphere, S2: gp_Torus) -> None: ...
    def Points(self, N: int, P1: Extrema_POnSurf, P2: Extrema_POnSurf) -> None: ...
    def SquareDistance(self, N: Optional[int] = 1) -> float: ...

class Extrema_ExtPElC:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, C: gp_Lin, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, C: gp_Circ, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, C: gp_Elips, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, C: gp_Hypr, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, C: gp_Parab, Tol: float, Uinf: float, Usup: float) -> None: ...
    def IsDone(self) -> bool: ...
    def IsMin(self, N: int) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, P: gp_Pnt, C: gp_Lin, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, C: gp_Circ, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, C: gp_Elips, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, C: gp_Hypr, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, C: gp_Parab, Tol: float, Uinf: float, Usup: float) -> None: ...
    def Point(self, N: int) -> Extrema_POnCurv: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtPElC2d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt2d, C: gp_Lin2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt2d, C: gp_Circ2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt2d, C: gp_Elips2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt2d, C: gp_Hypr2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt2d, C: gp_Parab2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    def IsDone(self) -> bool: ...
    def IsMin(self, N: int) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, P: gp_Pnt2d, L: gp_Lin2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt2d, C: gp_Circ2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt2d, C: gp_Elips2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt2d, C: gp_Hypr2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt2d, C: gp_Parab2d, Tol: float, Uinf: float, Usup: float) -> None: ...
    def Point(self, N: int) -> Extrema_POnCurv2d: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtPElS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: gp_Cylinder, Tol: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: gp_Pln, Tol: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: gp_Cone, Tol: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: gp_Torus, Tol: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: gp_Sphere, Tol: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, P: gp_Pnt, S: gp_Cylinder, Tol: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, S: gp_Pln, Tol: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, S: gp_Cone, Tol: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, S: gp_Torus, Tol: float) -> None: ...
    @overload
    def Perform(self, P: gp_Pnt, S: gp_Sphere, Tol: float) -> None: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtPExtS(Standard_Transient):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: GeomAdaptor_SurfaceOfLinearExtrusion, Umin: float, Usup: float, Vmin: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: GeomAdaptor_SurfaceOfLinearExtrusion, TolU: float, TolV: float) -> None: ...
    def Initialize(self, S: GeomAdaptor_SurfaceOfLinearExtrusion, Uinf: float, Usup: float, Vinf: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, P: gp_Pnt) -> None: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtPRevS(Standard_Transient):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: GeomAdaptor_SurfaceOfRevolution, Umin: float, Usup: float, Vmin: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: GeomAdaptor_SurfaceOfRevolution, TolU: float, TolV: float) -> None: ...
    def Initialize(self, S: GeomAdaptor_SurfaceOfRevolution, Umin: float, Usup: float, Vmin: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, P: gp_Pnt) -> None: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtPS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: Adaptor3d_Surface, TolU: float, TolV: float, F: Optional[Extrema_ExtFlag] = Extrema_ExtFlag_MINMAX, A: Optional[Extrema_ExtAlgo] = Extrema_ExtAlgo_Grad) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: Adaptor3d_Surface, Uinf: float, Usup: float, Vinf: float, Vsup: float, TolU: float, TolV: float, F: Optional[Extrema_ExtFlag] = Extrema_ExtFlag_MINMAX, A: Optional[Extrema_ExtAlgo] = Extrema_ExtAlgo_Grad) -> None: ...
    def Initialize(self, S: Adaptor3d_Surface, Uinf: float, Usup: float, Vinf: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, P: gp_Pnt) -> None: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SetAlgo(self, A: Extrema_ExtAlgo) -> None: ...
    def SetFlag(self, F: Extrema_ExtFlag) -> None: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_ExtSS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, TolS1: float, TolS2: float) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, Uinf1: float, Usup1: float, Vinf1: float, Vsup1: float, Uinf2: float, Usup2: float, Vinf2: float, Vsup2: float, TolS1: float, TolS2: float) -> None: ...
    def Initialize(self, S2: Adaptor3d_Surface, Uinf2: float, Usup2: float, Vinf2: float, Vsup2: float, TolS1: float) -> None: ...
    def IsDone(self) -> bool: ...
    def IsParallel(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, S1: Adaptor3d_Surface, Uinf1: float, Usup1: float, Vinf1: float, Vsup1: float, TolS1: float) -> None: ...
    def Points(self, N: int, P1: Extrema_POnSurf, P2: Extrema_POnSurf) -> None: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_FuncExtCS(math_FunctionSetWithDerivatives):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface) -> None: ...
    def Derivatives(self, UV: math_Vector, DF: math_Matrix) -> bool: ...
    def GetStateNumber(self) -> int: ...
    def Initialize(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface) -> None: ...
    def NbEquations(self) -> int: ...
    def NbExt(self) -> int: ...
    def NbVariables(self) -> int: ...
    def PointOnCurve(self, N: int) -> Extrema_POnCurv: ...
    def PointOnSurface(self, N: int) -> Extrema_POnSurf: ...
    def PointsOnCurve(self) -> False: ...
    def PointsOnSurf(self) -> False: ...
    def SquareDistance(self, N: int) -> float: ...
    def SquareDistances(self) -> False: ...
    def Value(self, UV: math_Vector, F: math_Vector) -> bool: ...
    def Values(self, UV: math_Vector, F: math_Vector, DF: math_Matrix) -> bool: ...

class Extrema_FuncExtSS(math_FunctionSetWithDerivatives):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface) -> None: ...
    def Derivatives(self, UV: math_Vector, DF: math_Matrix) -> bool: ...
    def GetStateNumber(self) -> int: ...
    def Initialize(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface) -> None: ...
    def NbEquations(self) -> int: ...
    def NbExt(self) -> int: ...
    def NbVariables(self) -> int: ...
    def PointOnS1(self, N: int) -> Extrema_POnSurf: ...
    def PointOnS2(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...
    def Value(self, UV: math_Vector, F: math_Vector) -> bool: ...
    def Values(self, UV: math_Vector, F: math_Vector, DF: math_Matrix) -> bool: ...

class Extrema_FuncPSDist(math_MultipleVarFunctionWithGradient):
    def __init__(self, theS: Adaptor3d_Surface, theP: gp_Pnt) -> None: ...
    def NbVariables(self) -> int: ...

class Extrema_FuncPSNorm(math_FunctionSetWithDerivatives):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: Adaptor3d_Surface) -> None: ...
    def Derivatives(self, UV: math_Vector, DF: math_Matrix) -> bool: ...
    def GetStateNumber(self) -> int: ...
    def Initialize(self, S: Adaptor3d_Surface) -> None: ...
    def NbEquations(self) -> int: ...
    def NbExt(self) -> int: ...
    def NbVariables(self) -> int: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SetPoint(self, P: gp_Pnt) -> None: ...
    def SquareDistance(self, N: int) -> float: ...
    def Value(self, UV: math_Vector, F: math_Vector) -> bool: ...
    def Values(self, UV: math_Vector, F: math_Vector, DF: math_Matrix) -> bool: ...

class Extrema_GGenExtCC_PointsInspector:
    def __init__(self, theTol: float) -> None: ...
    def ClearFind(self) -> None: ...
    def SetCurrent(self, theCurPnt: gp_XY) -> None: ...
    def isFind(self) -> bool: ...

class Extrema_GenExtCS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, NbT: int, NbU: int, NbV: int, Tol1: float, Tol2: float) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, NbT: int, NbU: int, NbV: int, tmin: float, tsup: float, Umin: float, Usup: float, Vmin: float, Vsup: float, Tol1: float, Tol2: float) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, NbU: int, NbV: int, Tol2: float) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, NbU: int, NbV: int, Umin: float, Usup: float, Vmin: float, Vsup: float, Tol2: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, C: Adaptor3d_Curve, NbT: int, Tol1: float) -> None: ...
    @overload
    def Perform(self, C: Adaptor3d_Curve, NbT: int, tmin: float, tsup: float, Tol1: float) -> None: ...
    def PointOnCurve(self, N: int) -> Extrema_POnCurv: ...
    def PointOnSurface(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_GenExtPS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: Adaptor3d_Surface, NbU: int, NbV: int, TolU: float, TolV: float, F: Optional[Extrema_ExtFlag] = Extrema_ExtFlag_MINMAX, A: Optional[Extrema_ExtAlgo] = Extrema_ExtAlgo_Grad) -> None: ...
    @overload
    def __init__(self, P: gp_Pnt, S: Adaptor3d_Surface, NbU: int, NbV: int, Umin: float, Usup: float, Vmin: float, Vsup: float, TolU: float, TolV: float, F: Optional[Extrema_ExtFlag] = Extrema_ExtFlag_MINMAX, A: Optional[Extrema_ExtAlgo] = Extrema_ExtAlgo_Grad) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, NbU: int, NbV: int, TolU: float, TolV: float) -> None: ...
    @overload
    def Initialize(self, S: Adaptor3d_Surface, NbU: int, NbV: int, Umin: float, Usup: float, Vmin: float, Vsup: float, TolU: float, TolV: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    def Perform(self, P: gp_Pnt) -> None: ...
    def Point(self, N: int) -> Extrema_POnSurf: ...
    def SetAlgo(self, A: Extrema_ExtAlgo) -> None: ...
    def SetFlag(self, F: Extrema_ExtFlag) -> None: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_GenExtSS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, NbU: int, NbV: int, Tol1: float, Tol2: float) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, NbU: int, NbV: int, U1min: float, U1sup: float, V1min: float, V1sup: float, U2min: float, U2sup: float, V2min: float, V2sup: float, Tol1: float, Tol2: float) -> None: ...
    @overload
    def Initialize(self, S2: Adaptor3d_Surface, NbU: int, NbV: int, Tol2: float) -> None: ...
    @overload
    def Initialize(self, S2: Adaptor3d_Surface, NbU: int, NbV: int, U2min: float, U2sup: float, V2min: float, V2sup: float, Tol2: float) -> None: ...
    def IsDone(self) -> bool: ...
    def NbExt(self) -> int: ...
    @overload
    def Perform(self, S1: Adaptor3d_Surface, Tol1: float) -> None: ...
    @overload
    def Perform(self, S1: Adaptor3d_Surface, U1min: float, U1sup: float, V1min: float, V1sup: float, Tol1: float) -> None: ...
    def PointOnS1(self, N: int) -> Extrema_POnSurf: ...
    def PointOnS2(self, N: int) -> Extrema_POnSurf: ...
    def SquareDistance(self, N: int) -> float: ...

class Extrema_GenLocateExtCS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, T: float, U: float, V: float, Tol1: float, Tol2: float) -> None: ...
    def IsDone(self) -> bool: ...
    def Perform(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface, T: float, U: float, V: float, Tol1: float, Tol2: float) -> None: ...
    def PointOnCurve(self) -> Extrema_POnCurv: ...
    def PointOnSurface(self) -> Extrema_POnSurf: ...
    def SquareDistance(self) -> float: ...

class Extrema_GenLocateExtPS:
    def __init__(self, theS: Adaptor3d_Surface, theTolU: Optional[float] = Precision.PConfusion(), theTolV: Optional[float] = Precision.PConfusion()) -> None: ...
    def IsDone(self) -> bool: ...
    @staticmethod
    def IsMinDist(theP: gp_Pnt, theS: Adaptor3d_Surface, theU0: float, theV0: float) -> bool: ...
    def Perform(self, theP: gp_Pnt, theU0: float, theV0: float, isDistanceCriteria: Optional[bool] = false) -> None: ...
    def Point(self) -> Extrema_POnSurf: ...
    def SquareDistance(self) -> float: ...

class Extrema_GenLocateExtSS:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, U1: float, V1: float, U2: float, V2: float, Tol1: float, Tol2: float) -> None: ...
    def IsDone(self) -> bool: ...
    def Perform(self, S1: Adaptor3d_Surface, S2: Adaptor3d_Surface, U1: float, V1: float, U2: float, V2: float, Tol1: float, Tol2: float) -> None: ...
    def PointOnS1(self) -> Extrema_POnSurf: ...
    def PointOnS2(self) -> Extrema_POnSurf: ...
    def SquareDistance(self) -> float: ...

class Extrema_GlobOptFuncCCC0(math_MultipleVarFunction):
    @overload
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve) -> None: ...
    @overload
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d) -> None: ...
    def NbVariables(self) -> int: ...

class Extrema_GlobOptFuncCCC1(math_MultipleVarFunctionWithGradient):
    @overload
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve) -> None: ...
    @overload
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d) -> None: ...
    def Gradient(self, X: math_Vector, G: math_Vector) -> bool: ...
    def NbVariables(self) -> int: ...

class Extrema_GlobOptFuncCCC2(math_MultipleVarFunctionWithHessian):
    @overload
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve) -> None: ...
    @overload
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d) -> None: ...
    def Gradient(self, X: math_Vector, G: math_Vector) -> bool: ...
    def NbVariables(self) -> int: ...

class Extrema_GlobOptFuncCQuadric(math_MultipleVarFunction):
    @overload
    def __init__(self, C: Adaptor3d_Curve) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, theTf: float, theTl: float) -> None: ...
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface) -> None: ...
    def LoadQuad(self, S: Adaptor3d_Surface, theUf: float, theUl: float, theVf: float, theVl: float) -> None: ...
    def NbVariables(self) -> int: ...
    def QuadricParameters(self, theCT: math_Vector, theUV: math_Vector) -> None: ...

class Extrema_GlobOptFuncCS(math_MultipleVarFunctionWithHessian):
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface) -> None: ...
    def Gradient(self, theX: math_Vector, theG: math_Vector) -> bool: ...
    def NbVariables(self) -> int: ...

class Extrema_GlobOptFuncConicS(math_MultipleVarFunction):
    @overload
    def __init__(self, C: Adaptor3d_Curve, S: Adaptor3d_Surface) -> None: ...
    @overload
    def __init__(self, S: Adaptor3d_Surface) -> None: ...
    @overload
    def __init__(self, S: Adaptor3d_Surface, theUf: float, theUl: float, theVf: float, theVl: float) -> None: ...
    def ConicParameter(self, theUV: math_Vector) -> float: ...
    def LoadConic(self, S: Adaptor3d_Curve, theTf: float, theTl: float) -> None: ...
    def NbVariables(self) -> int: ...

class Extrema_LocateExtCC:
    def __init__(self, C1: Adaptor3d_Curve, C2: Adaptor3d_Curve, U0: float, V0: float) -> None: ...
    def IsDone(self) -> bool: ...
    def Point(self, P1: Extrema_POnCurv, P2: Extrema_POnCurv) -> None: ...
    def SquareDistance(self) -> float: ...

class Extrema_LocateExtCC2d:
    def __init__(self, C1: Adaptor2d_Curve2d, C2: Adaptor2d_Curve2d, U0: float, V0: float) -> None: ...
    def IsDone(self) -> bool: ...
    def Point(self, P1: Extrema_POnCurv2d, P2: Extrema_POnCurv2d) -> None: ...
    def SquareDistance(self) -> float: ...

class Extrema_POnCurv:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theU: float, theP: gp_Pnt) -> None: ...
    def Parameter(self) -> float: ...
    def SetValues(self, theU: float, theP: gp_Pnt) -> None: ...
    def Value(self) -> gp_Pnt: ...

class Extrema_POnCurv2d:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theU: float, theP: gp_Pnt2d) -> None: ...
    def Parameter(self) -> float: ...
    def SetValues(self, theU: float, theP: gp_Pnt2d) -> None: ...
    def Value(self) -> gp_Pnt2d: ...

class Extrema_POnSurf:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theU: float, theV: float, theP: gp_Pnt) -> None: ...
    def SetParameters(self, theU: float, theV: float, thePnt: gp_Pnt) -> None: ...
    def Value(self) -> gp_Pnt: ...

class Extrema_POnSurfParams(Extrema_POnSurf):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theU: float, theV: float, thePnt: gp_Pnt) -> None: ...
    def GetElementType(self) -> Extrema_ElementType: ...
    def GetSqrDistance(self) -> float: ...
    def SetElementType(self, theElementType: Extrema_ElementType) -> None: ...
    def SetIndices(self, theIndexU: int, theIndexV: int) -> None: ...
    def SetSqrDistance(self, theSqrDistance: float) -> None: ...

# harray1 classes

class Extrema_HArray1OfPOnCurv(NCollection_Array1<Extrema_POnCurv>, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> NCollection_Array1<Extrema_POnCurv>: ...


class Extrema_HArray1OfPOnCurv2d(NCollection_Array1<Extrema_POnCurv2d>, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> NCollection_Array1<Extrema_POnCurv2d>: ...


class Extrema_HArray1OfPOnSurf(NCollection_Array1<Extrema_POnSurf>, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> NCollection_Array1<Extrema_POnSurf>: ...

# harray2 classes

class Extrema_HArray2OfPOnCurv(NCollection_Array2<Extrema_POnCurv>, Standard_Transient):
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2<Extrema_POnCurv>) -> None: ...
    def Array2(self) -> NCollection_Array2<Extrema_POnCurv>: ...


class Extrema_HArray2OfPOnCurv2d(NCollection_Array2<Extrema_POnCurv2d>, Standard_Transient):
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2<Extrema_POnCurv2d>) -> None: ...
    def Array2(self) -> NCollection_Array2<Extrema_POnCurv2d>: ...


class Extrema_HArray2OfPOnSurf(NCollection_Array2<Extrema_POnSurf>, Standard_Transient):
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2<Extrema_POnSurf>) -> None: ...
    def Array2(self) -> NCollection_Array2<Extrema_POnSurf>: ...

# hsequence classes

