from enum import IntEnum
from typing import overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.IGESData import *
from OCC.Core.TColStd import *
from OCC.Core.TCollection import *
from OCC.Core.Interface import *
from OCC.Core.TColgp import *
from OCC.Core.gp import *

#the following typedef cannot be wrapped as is
IGESBasic_Array2OfHArray1OfReal = NewType('IGESBasic_Array2OfHArray1OfReal', Any)

class IGESBasic_Array1OfLineFontEntity:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def __getitem__(self, index: int) -> False: ...
    def __setitem__(self, index: int, value: False) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[False]: ...
    def next(self) -> False: ...
    __next__ = next
    def Init(self, theValue: False) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDetectable(self) -> bool: ...
    def IsAllocated(self) -> bool: ...
    def First(self) -> False: ...
    def Last(self) -> False: ...
    def Value(self, theIndex: int) -> False: ...
    def SetValue(self, theIndex: int, theValue: False) -> None: ...

class igesbasic:
    @staticmethod
    def Init() -> None: ...
    @staticmethod
    def Protocol() -> IGESBasic_Protocol: ...

class IGESBasic_AssocGroupType(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def AssocType(self) -> int: ...
    def Init(self, nbDataFields: int, aType: int, aName: TCollection_HAsciiString) -> None: ...
    def Name(self) -> TCollection_HAsciiString: ...
    def NbData(self) -> int: ...

class IGESBasic_ExternalRefFile(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def FileId(self) -> TCollection_HAsciiString: ...
    def Init(self, aFileIdent: TCollection_HAsciiString) -> None: ...

class IGESBasic_ExternalRefFileIndex(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def Entity(self, Index: int) -> IGESData_IGESEntity: ...
    def Init(self, aNameArray: Interface_HArray1OfHAsciiString, allEntities: IGESData_HArray1OfIGESEntity) -> None: ...
    def Name(self, Index: int) -> TCollection_HAsciiString: ...
    def NbEntries(self) -> int: ...

class IGESBasic_ExternalRefFileName(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def FileId(self) -> TCollection_HAsciiString: ...
    def Init(self, aFileIdent: TCollection_HAsciiString, anExtName: TCollection_HAsciiString) -> None: ...
    def ReferenceName(self) -> TCollection_HAsciiString: ...
    def SetForEntity(self, mode: bool) -> None: ...

class IGESBasic_ExternalRefLibName(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def Init(self, aLibName: TCollection_HAsciiString, anExtName: TCollection_HAsciiString) -> None: ...
    def LibraryName(self) -> TCollection_HAsciiString: ...
    def ReferenceName(self) -> TCollection_HAsciiString: ...

class IGESBasic_ExternalRefName(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def Init(self, anExtName: TCollection_HAsciiString) -> None: ...
    def ReferenceName(self) -> TCollection_HAsciiString: ...

class IGESBasic_ExternalReferenceFile(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def Init(self, aNameArray: Interface_HArray1OfHAsciiString) -> None: ...
    def Name(self, Index: int) -> TCollection_HAsciiString: ...
    def NbListEntries(self) -> int: ...

class IGESBasic_GeneralModule(IGESData_GeneralModule):
    def __init__(self) -> None: ...
    def CategoryNumber(self, CN: int, ent: Standard_Transient, shares: Interface_ShareTool) -> int: ...
    def DirChecker(self, CN: int, ent: IGESData_IGESEntity) -> IGESData_DirChecker: ...
    def NewVoid(self, CN: int, entto: Standard_Transient) -> bool: ...
    def OwnCheckCase(self, CN: int, ent: IGESData_IGESEntity, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopyCase(self, CN: int, entfrom: IGESData_IGESEntity, entto: IGESData_IGESEntity, TC: Interface_CopyTool) -> None: ...
    def OwnSharedCase(self, CN: int, ent: IGESData_IGESEntity, iter: Interface_EntityIterator) -> None: ...

class IGESBasic_Group(IGESData_IGESEntity):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, nb: int) -> None: ...
    def Entity(self, Index: int) -> IGESData_IGESEntity: ...
    def Init(self, allEntities: IGESData_HArray1OfIGESEntity) -> None: ...
    def IsOrdered(self) -> bool: ...
    def IsWithoutBackP(self) -> bool: ...
    def NbEntities(self) -> int: ...
    def SetNb(self, nb: int) -> None: ...
    def SetOrdered(self, mode: bool) -> None: ...
    def SetUser(self, type: int, form: int) -> None: ...
    def SetValue(self, Index: int, ent: IGESData_IGESEntity) -> None: ...
    def SetWithoutBackP(self, mode: bool) -> None: ...
    def Value(self, Index: int) -> Standard_Transient: ...

class IGESBasic_HArray1OfHArray1OfIGESEntity(Standard_Transient):
    def __init__(self, low: int, up: int) -> None: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def SetValue(self, num: int, val: IGESData_HArray1OfIGESEntity) -> None: ...
    def Upper(self) -> int: ...
    def Value(self, num: int) -> IGESData_HArray1OfIGESEntity: ...

class IGESBasic_HArray1OfHArray1OfInteger(Standard_Transient):
    def __init__(self, low: int, up: int) -> None: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def SetValue(self, num: int, val: TColStd_HArray1OfInteger) -> None: ...
    def Upper(self) -> int: ...
    def Value(self, num: int) -> TColStd_HArray1OfInteger: ...

class IGESBasic_HArray1OfHArray1OfReal(Standard_Transient):
    def __init__(self, low: int, up: int) -> None: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def SetValue(self, num: int, val: TColStd_HArray1OfReal) -> None: ...
    def Upper(self) -> int: ...
    def Value(self, num: int) -> TColStd_HArray1OfReal: ...

class IGESBasic_HArray1OfHArray1OfXY(Standard_Transient):
    def __init__(self, low: int, up: int) -> None: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def SetValue(self, num: int, val: TColgp_HArray1OfXY) -> None: ...
    def Upper(self) -> int: ...
    def Value(self, num: int) -> TColgp_HArray1OfXY: ...

class IGESBasic_HArray1OfHArray1OfXYZ(Standard_Transient):
    def __init__(self, low: int, up: int) -> None: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def SetValue(self, num: int, val: TColgp_HArray1OfXYZ) -> None: ...
    def Upper(self) -> int: ...
    def Value(self, num: int) -> TColgp_HArray1OfXYZ: ...

class IGESBasic_Hierarchy(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def Init(self, nbPropVal: int, aLineFont: int, aView: int, anEntityLevel: int, aBlankStatus: int, aLineWt: int, aColorNum: int) -> None: ...
    def NbPropertyValues(self) -> int: ...
    def NewBlankStatus(self) -> int: ...
    def NewColorNum(self) -> int: ...
    def NewEntityLevel(self) -> int: ...
    def NewLineFont(self) -> int: ...
    def NewLineWeight(self) -> int: ...
    def NewView(self) -> int: ...

class IGESBasic_Name(IGESData_NameEntity):
    def __init__(self) -> None: ...
    def Init(self, nbPropVal: int, aName: TCollection_HAsciiString) -> None: ...
    def NbPropertyValues(self) -> int: ...
    def Value(self) -> TCollection_HAsciiString: ...

class IGESBasic_Protocol(IGESData_Protocol):
    def __init__(self) -> None: ...
    def NbResources(self) -> int: ...
    def Resource(self, num: int) -> Interface_Protocol: ...
    def TypeNumber(self, atype: Standard_Type) -> int: ...

class IGESBasic_ReadWriteModule(IGESData_ReadWriteModule):
    def __init__(self) -> None: ...
    def CaseIGES(self, typenum: int, formnum: int) -> int: ...
    def ReadOwnParams(self, CN: int, ent: IGESData_IGESEntity, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, CN: int, ent: IGESData_IGESEntity, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_SingleParent(IGESData_SingleParentEntity):
    def __init__(self) -> None: ...
    def Child(self, Index: int) -> IGESData_IGESEntity: ...
    def Init(self, nbParentEntities: int, aParentEntity: IGESData_IGESEntity, allChildren: IGESData_HArray1OfIGESEntity) -> None: ...
    def NbChildren(self) -> int: ...
    def NbParentEntities(self) -> int: ...
    def SingleParent(self) -> IGESData_IGESEntity: ...

class IGESBasic_SingularSubfigure(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def HasScaleFactor(self) -> bool: ...
    def Init(self, aSubfigureDef: IGESBasic_SubfigureDef, aTranslation: gp_XYZ, hasScale: bool, aScale: float) -> None: ...
    def ScaleFactor(self) -> float: ...
    def Subfigure(self) -> IGESBasic_SubfigureDef: ...
    def TransformedTranslation(self) -> gp_XYZ: ...
    def Translation(self) -> gp_XYZ: ...

class IGESBasic_SpecificModule(IGESData_SpecificModule):
    def __init__(self) -> None: ...
    def OwnCorrect(self, CN: int, ent: IGESData_IGESEntity) -> bool: ...

class IGESBasic_SubfigureDef(IGESData_IGESEntity):
    def __init__(self) -> None: ...
    def AssociatedEntity(self, Index: int) -> IGESData_IGESEntity: ...
    def Depth(self) -> int: ...
    def Init(self, aDepth: int, aName: TCollection_HAsciiString, allAssocEntities: IGESData_HArray1OfIGESEntity) -> None: ...
    def Name(self) -> TCollection_HAsciiString: ...
    def NbEntities(self) -> int: ...
    def Value(self, Index: int) -> Standard_Transient: ...

class IGESBasic_ToolAssocGroupType:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_AssocGroupType) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_AssocGroupType, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_AssocGroupType, entto: IGESBasic_AssocGroupType, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_AssocGroupType) -> bool: ...
    def OwnShared(self, ent: IGESBasic_AssocGroupType, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_AssocGroupType, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_AssocGroupType, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalRefFile:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalRefFile) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalRefFile, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalRefFile, entto: IGESBasic_ExternalRefFile, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalRefFile, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalRefFile, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalRefFile, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalRefFileIndex:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalRefFileIndex) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalRefFileIndex, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalRefFileIndex, entto: IGESBasic_ExternalRefFileIndex, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalRefFileIndex, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalRefFileIndex, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalRefFileIndex, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalRefFileName:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalRefFileName) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalRefFileName, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalRefFileName, entto: IGESBasic_ExternalRefFileName, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalRefFileName, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalRefFileName, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalRefFileName, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalRefLibName:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalRefLibName) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalRefLibName, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalRefLibName, entto: IGESBasic_ExternalRefLibName, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalRefLibName, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalRefLibName, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalRefLibName, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalRefName:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalRefName) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalRefName, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalRefName, entto: IGESBasic_ExternalRefName, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalRefName, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalRefName, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalRefName, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolExternalReferenceFile:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_ExternalReferenceFile) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_ExternalReferenceFile, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_ExternalReferenceFile, entto: IGESBasic_ExternalReferenceFile, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_ExternalReferenceFile, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_ExternalReferenceFile, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_ExternalReferenceFile, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolGroup:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_Group) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_Group, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_Group, entto: IGESBasic_Group, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_Group) -> bool: ...
    def OwnShared(self, ent: IGESBasic_Group, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_Group, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_Group, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolGroupWithoutBackP:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_GroupWithoutBackP) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_GroupWithoutBackP, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_GroupWithoutBackP, entto: IGESBasic_GroupWithoutBackP, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_GroupWithoutBackP) -> bool: ...
    def OwnShared(self, ent: IGESBasic_GroupWithoutBackP, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_GroupWithoutBackP, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_GroupWithoutBackP, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolHierarchy:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_Hierarchy) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_Hierarchy, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_Hierarchy, entto: IGESBasic_Hierarchy, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_Hierarchy) -> bool: ...
    def OwnShared(self, ent: IGESBasic_Hierarchy, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_Hierarchy, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_Hierarchy, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolName:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_Name) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_Name, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_Name, entto: IGESBasic_Name, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_Name) -> bool: ...
    def OwnShared(self, ent: IGESBasic_Name, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_Name, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_Name, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolOrderedGroup:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_OrderedGroup) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_OrderedGroup, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_OrderedGroup, entto: IGESBasic_OrderedGroup, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_OrderedGroup) -> bool: ...
    def OwnShared(self, ent: IGESBasic_OrderedGroup, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_OrderedGroup, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_OrderedGroup, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolOrderedGroupWithoutBackP:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_OrderedGroupWithoutBackP) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_OrderedGroupWithoutBackP, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_OrderedGroupWithoutBackP, entto: IGESBasic_OrderedGroupWithoutBackP, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_OrderedGroupWithoutBackP) -> bool: ...
    def OwnShared(self, ent: IGESBasic_OrderedGroupWithoutBackP, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_OrderedGroupWithoutBackP, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_OrderedGroupWithoutBackP, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolSingleParent:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_SingleParent) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_SingleParent, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_SingleParent, entto: IGESBasic_SingleParent, TC: Interface_CopyTool) -> None: ...
    def OwnCorrect(self, ent: IGESBasic_SingleParent) -> bool: ...
    def OwnShared(self, ent: IGESBasic_SingleParent, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_SingleParent, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_SingleParent, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolSingularSubfigure:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_SingularSubfigure) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_SingularSubfigure, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_SingularSubfigure, entto: IGESBasic_SingularSubfigure, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_SingularSubfigure, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_SingularSubfigure, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_SingularSubfigure, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_ToolSubfigureDef:
    def __init__(self) -> None: ...
    def DirChecker(self, ent: IGESBasic_SubfigureDef) -> IGESData_DirChecker: ...
    def OwnCheck(self, ent: IGESBasic_SubfigureDef, shares: Interface_ShareTool, ach: Interface_Check) -> None: ...
    def OwnCopy(self, entfrom: IGESBasic_SubfigureDef, entto: IGESBasic_SubfigureDef, TC: Interface_CopyTool) -> None: ...
    def OwnShared(self, ent: IGESBasic_SubfigureDef, iter: Interface_EntityIterator) -> None: ...
    def ReadOwnParams(self, ent: IGESBasic_SubfigureDef, IR: IGESData_IGESReaderData, PR: IGESData_ParamReader) -> None: ...
    def WriteOwnParams(self, ent: IGESBasic_SubfigureDef, IW: IGESData_IGESWriter) -> None: ...

class IGESBasic_GroupWithoutBackP(IGESBasic_Group):
    def __init__(self) -> None: ...

class IGESBasic_OrderedGroup(IGESBasic_Group):
    def __init__(self) -> None: ...

class IGESBasic_OrderedGroupWithoutBackP(IGESBasic_Group):
    def __init__(self) -> None: ...

# harray1 classes

class IGESBasic_HArray1OfLineFontEntity(IGESBasic_Array1OfLineFontEntity, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> IGESBasic_Array1OfLineFontEntity: ...

# harray2 classes

class IGESBasic_HArray2OfHArray1OfReal(IGESBasic_Array2OfHArray1OfReal, Standard_Transient):
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theOther: IGESBasic_Array2OfHArray1OfReal) -> None: ...
    def Array2(self) -> IGESBasic_Array2OfHArray1OfReal: ...

# hsequence classes

igesbasic_Init = igesbasic.Init
igesbasic_Protocol = igesbasic.Protocol
