from typing import NewType, Optional, Tuple

from OCC.Core.Intrv import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *


class Intrv_Position:
	Intrv_Before: int = ...
	Intrv_JustBefore: int = ...
	Intrv_OverlappingAtStart: int = ...
	Intrv_JustEnclosingAtEnd: int = ...
	Intrv_Enclosing: int = ...
	Intrv_JustOverlappingAtStart: int = ...
	Intrv_Similar: int = ...
	Intrv_JustEnclosingAtStart: int = ...
	Intrv_Inside: int = ...
	Intrv_JustOverlappingAtEnd: int = ...
	Intrv_OverlappingAtEnd: int = ...
	Intrv_JustAfter: int = ...
	Intrv_After: int = ...

class Intrv_Interval:
	def __init__(self) -> None: ...
	def __init__(self, Start: float, End: float) -> None: ...
	def __init__(self, Start: float, TolStart: Standard_ShortReal, End: float, TolEnd: Standard_ShortReal) -> None: ...
	def Bounds(self, TolStart: Standard_ShortReal, TolEnd: Standard_ShortReal) -> Tuple[float, float]: ...
	def CutAtEnd(self, End: float, TolEnd: Standard_ShortReal) -> None: ...
	def CutAtStart(self, Start: float, TolStart: Standard_ShortReal) -> None: ...
	def End(self) -> float: ...
	def FuseAtEnd(self, End: float, TolEnd: Standard_ShortReal) -> None: ...
	def FuseAtStart(self, Start: float, TolStart: Standard_ShortReal) -> None: ...
	def IsAfter(self, Other: Intrv_Interval) -> bool: ...
	def IsBefore(self, Other: Intrv_Interval) -> bool: ...
	def IsEnclosing(self, Other: Intrv_Interval) -> bool: ...
	def IsInside(self, Other: Intrv_Interval) -> bool: ...
	def IsJustAfter(self, Other: Intrv_Interval) -> bool: ...
	def IsJustBefore(self, Other: Intrv_Interval) -> bool: ...
	def IsJustEnclosingAtEnd(self, Other: Intrv_Interval) -> bool: ...
	def IsJustEnclosingAtStart(self, Other: Intrv_Interval) -> bool: ...
	def IsJustOverlappingAtEnd(self, Other: Intrv_Interval) -> bool: ...
	def IsJustOverlappingAtStart(self, Other: Intrv_Interval) -> bool: ...
	def IsOverlappingAtEnd(self, Other: Intrv_Interval) -> bool: ...
	def IsOverlappingAtStart(self, Other: Intrv_Interval) -> bool: ...
	def IsProbablyEmpty(self) -> bool: ...
	def IsSimilar(self, Other: Intrv_Interval) -> bool: ...
	def Position(self, Other: Intrv_Interval) -> Intrv_Position: ...
	def SetEnd(self, End: float, TolEnd: Standard_ShortReal) -> None: ...
	def SetStart(self, Start: float, TolStart: Standard_ShortReal) -> None: ...
	def Start(self) -> float: ...
	def TolEnd(self) -> Standard_ShortReal: ...
	def TolStart(self) -> Standard_ShortReal: ...

class Intrv_Intervals:
	def __init__(self) -> None: ...
	def __init__(self, Int: Intrv_Interval) -> None: ...
	def __init__(self, Int: Intrv_Intervals) -> None: ...
	def Intersect(self, Tool: Intrv_Interval) -> None: ...
	def Intersect(self, Tool: Intrv_Intervals) -> None: ...
	def NbIntervals(self) -> int: ...
	def Subtract(self, Tool: Intrv_Interval) -> None: ...
	def Subtract(self, Tool: Intrv_Intervals) -> None: ...
	def Unite(self, Tool: Intrv_Interval) -> None: ...
	def Unite(self, Tool: Intrv_Intervals) -> None: ...
	def Value(self, Index: int) -> Intrv_Interval: ...
	def XUnite(self, Tool: Intrv_Interval) -> None: ...
	def XUnite(self, Tool: Intrv_Intervals) -> None: ...
