from enum import IntEnum
import typing
from typing import Any, overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TopoDS import *
from OCC.Core.ShapeBuild import *
from OCC.Core.Message import *
from OCC.Core.ShapeExtend import *
from OCC.Core.Geom import *
from OCC.Core.TopLoc import *
from OCC.Core.ShapeAnalysis import *
from OCC.Core.ShapeConstruct import *
from OCC.Core.Geom2d import *
from OCC.Core.TopAbs import *
from OCC.Core.TopTools import *


class ShapeFix_SequenceOfWireSegment:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def First(self) -> ShapeFix_WireSegment: ...
    def Last(self) -> ShapeFix_WireSegment: ...
    def Length(self) -> int: ...
    def Append(self, theItem: ShapeFix_WireSegment) -> ShapeFix_WireSegment: ...
    def Prepend(self, theItem: ShapeFix_WireSegment) -> ShapeFix_WireSegment: ...
    def RemoveFirst(self) -> None: ...
    def Reverse(self) -> None: ...
    def Value(self, theIndex: int) -> ShapeFix_WireSegment: ...
    def SetValue(self, theIndex: int, theValue: ShapeFix_WireSegment) -> None: ...

class ShapeFix_DataMapOfShapeBox2d:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class shapefix:
    @staticmethod
    def EncodeRegularity(shape: TopoDS_Shape, tolang: Optional[float] = 1.0e-10) -> None: ...
    @staticmethod
    def FixVertexPosition(theshape: TopoDS_Shape, theTolerance: float, thecontext: ShapeBuild_ReShape) -> bool: ...
    @staticmethod
    def LeastEdgeSize(theshape: TopoDS_Shape) -> float: ...
    @staticmethod
    def RemoveSmallEdges(shape: TopoDS_Shape, Tolerance: float, context: ShapeBuild_ReShape) -> TopoDS_Shape: ...
    @staticmethod
    def SameParameter(shape: TopoDS_Shape, enforce: bool, preci: Optional[float] = 0.0, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange(), theMsgReg: Optional[ShapeExtend_BasicMsgRegistrator] = None) -> bool: ...

class ShapeFix_Edge(Standard_Transient):
    def __init__(self) -> None: ...
    def FixAddCurve3d(self, edge: TopoDS_Edge) -> bool: ...
    @overload
    def FixAddPCurve(self, edge: TopoDS_Edge, face: TopoDS_Face, isSeam: bool, prec: Optional[float] = 0.0) -> bool: ...
    @overload
    def FixAddPCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location, isSeam: bool, prec: Optional[float] = 0.0) -> bool: ...
    @overload
    def FixAddPCurve(self, edge: TopoDS_Edge, face: TopoDS_Face, isSeam: bool, surfana: ShapeAnalysis_Surface, prec: Optional[float] = 0.0) -> bool: ...
    @overload
    def FixAddPCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location, isSeam: bool, surfana: ShapeAnalysis_Surface, prec: Optional[float] = 0.0) -> bool: ...
    def FixRemoveCurve3d(self, edge: TopoDS_Edge) -> bool: ...
    @overload
    def FixRemovePCurve(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
    @overload
    def FixRemovePCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location) -> bool: ...
    @overload
    def FixReversed2d(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
    @overload
    def FixReversed2d(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location) -> bool: ...
    @overload
    def FixSameParameter(self, edge: TopoDS_Edge, tolerance: Optional[float] = 0.0) -> bool: ...
    @overload
    def FixSameParameter(self, edge: TopoDS_Edge, face: TopoDS_Face, tolerance: Optional[float] = 0.0) -> bool: ...
    @overload
    def FixVertexTolerance(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
    @overload
    def FixVertexTolerance(self, edge: TopoDS_Edge) -> bool: ...
    def Projector(self) -> ShapeConstruct_ProjectCurveOnSurface: ...
    def SetContext(self, context: ShapeBuild_ReShape) -> None: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_EdgeConnect:
    def __init__(self) -> None: ...
    @overload
    def Add(self, aFirst: TopoDS_Edge, aSecond: TopoDS_Edge) -> None: ...
    @overload
    def Add(self, aShape: TopoDS_Shape) -> None: ...
    def Build(self) -> None: ...
    def Clear(self) -> None: ...

class ShapeFix_EdgeProjAux(Standard_Transient):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, F: TopoDS_Face, E: TopoDS_Edge) -> None: ...
    def Compute(self, preci: float) -> None: ...
    def FirstParam(self) -> float: ...
    def Init(self, F: TopoDS_Face, E: TopoDS_Edge) -> None: ...
    def IsFirstDone(self) -> bool: ...
    def IsIso(self, C: Geom2d_Curve) -> bool: ...
    def IsLastDone(self) -> bool: ...
    def LastParam(self) -> float: ...

class ShapeFix_FaceConnect:
    def __init__(self) -> None: ...
    def Add(self, aFirst: TopoDS_Face, aSecond: TopoDS_Face) -> bool: ...
    def Build(self, shell: TopoDS_Shell, sewtoler: float, fixtoler: float) -> TopoDS_Shell: ...
    def Clear(self) -> None: ...

class ShapeFix_FreeBounds:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, shape: TopoDS_Shape, sewtoler: float, closetoler: float, splitclosed: bool, splitopen: bool) -> None: ...
    @overload
    def __init__(self, shape: TopoDS_Shape, closetoler: float, splitclosed: bool, splitopen: bool) -> None: ...
    def GetClosedWires(self) -> TopoDS_Compound: ...
    def GetOpenWires(self) -> TopoDS_Compound: ...
    def GetShape(self) -> TopoDS_Shape: ...

class ShapeFix_IntersectionTool:
    def __init__(self, context: ShapeBuild_ReShape, preci: float, maxtol: Optional[float] = 1.0) -> None: ...
    def Context(self) -> ShapeBuild_ReShape: ...
    def CutEdge(self, edge: TopoDS_Edge, pend: float, cut: float, face: TopoDS_Face) -> Tuple[bool, bool]: ...
    def FixIntersectingWires(self, face: TopoDS_Face) -> bool: ...
    def FixSelfIntersectWire(self, sewd: ShapeExtend_WireData, face: TopoDS_Face) -> Tuple[bool, int, int, int]: ...
    def SplitEdge(self, edge: TopoDS_Edge, param: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, preci: float) -> bool: ...

class ShapeFix_Root(Standard_Transient):
    def __init__(self) -> None: ...
    def Context(self) -> ShapeBuild_ReShape: ...
    def LimitTolerance(self, toler: float) -> float: ...
    def MaxTolerance(self) -> float: ...
    def MinTolerance(self) -> float: ...
    def MsgRegistrator(self) -> ShapeExtend_BasicMsgRegistrator: ...
    def Precision(self) -> float: ...
    @overload
    def SendFail(self, shape: TopoDS_Shape, message: Message_Msg) -> None: ...
    @overload
    def SendFail(self, message: Message_Msg) -> None: ...
    @overload
    def SendMsg(self, shape: TopoDS_Shape, message: Message_Msg, gravity: Optional[Message_Gravity] = Message_Info) -> None: ...
    @overload
    def SendMsg(self, message: Message_Msg, gravity: Optional[Message_Gravity] = Message_Info) -> None: ...
    @overload
    def SendWarning(self, shape: TopoDS_Shape, message: Message_Msg) -> None: ...
    @overload
    def SendWarning(self, message: Message_Msg) -> None: ...
    def Set(self, Root: ShapeFix_Root) -> None: ...
    def SetContext(self, context: ShapeBuild_ReShape) -> None: ...
    def SetMaxTolerance(self, maxtol: float) -> None: ...
    def SetMinTolerance(self, mintol: float) -> None: ...
    def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
    def SetPrecision(self, preci: float) -> None: ...

class ShapeFix_ShapeTolerance:
    def __init__(self) -> None: ...
    def LimitTolerance(self, shape: TopoDS_Shape, tmin: float, tmax: Optional[float] = 0.0, styp: Optional[TopAbs_ShapeEnum] = TopAbs_SHAPE) -> bool: ...
    def SetTolerance(self, shape: TopoDS_Shape, preci: float, styp: Optional[TopAbs_ShapeEnum] = TopAbs_SHAPE) -> None: ...

class ShapeFix_SplitTool:
    def __init__(self) -> None: ...
    def CutEdge(self, edge: TopoDS_Edge, pend: float, cut: float, face: TopoDS_Face) -> Tuple[bool, bool]: ...
    @overload
    def SplitEdge(self, edge: TopoDS_Edge, param: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, tol3d: float, tol2d: float) -> bool: ...
    @overload
    def SplitEdge(self, edge: TopoDS_Edge, param1: float, param2: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, tol3d: float, tol2d: float) -> bool: ...
    @overload
    def SplitEdge(self, edge: TopoDS_Edge, fp: float, V1: TopoDS_Vertex, lp: float, V2: TopoDS_Vertex, face: TopoDS_Face, SeqE: TopTools_SequenceOfShape, context: ShapeBuild_ReShape, tol3d: float, tol2d: float) -> Tuple[bool, int]: ...

class ShapeFix_WireVertex:
    def __init__(self) -> None: ...
    def Analyzer(self) -> ShapeAnalysis_WireVertex: ...
    def Fix(self) -> int: ...
    def FixSame(self) -> int: ...
    @overload
    def Init(self, wire: TopoDS_Wire, preci: float) -> None: ...
    @overload
    def Init(self, sbwd: ShapeExtend_WireData, preci: float) -> None: ...
    @overload
    def Init(self, sawv: ShapeAnalysis_WireVertex) -> None: ...
    def Wire(self) -> TopoDS_Wire: ...
    def WireData(self) -> ShapeExtend_WireData: ...

class ShapeFix_ComposeShell(ShapeFix_Root):
    def __init__(self) -> None: ...
    def ClosedMode(self) -> bool: ...
    def DispatchWires(self, faces: TopTools_SequenceOfShape, wires: Any) -> None: ...
    def GetTransferParamTool(self) -> ShapeAnalysis_TransferParameters: ...
    def Init(self, Grid: ShapeExtend_CompositeSurface, L: TopLoc_Location, Face: TopoDS_Face, Prec: float) -> None: ...
    def Perform(self) -> bool: ...
    def Result(self) -> TopoDS_Shape: ...
    def SetTransferParamTool(self, TransferParam: ShapeAnalysis_TransferParameters) -> None: ...
    def SplitEdges(self) -> None: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Face(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, face: TopoDS_Face) -> None: ...
    def Add(self, wire: TopoDS_Wire) -> None: ...
    def AutoCorrectPrecisionMode(self) -> Any: ...
    def ClearModes(self) -> None: ...
    def Face(self) -> TopoDS_Face: ...
    def FixAddNaturalBound(self) -> bool: ...
    def FixAddNaturalBoundMode(self) -> Any: ...
    def FixIntersectingWires(self) -> bool: ...
    def FixIntersectingWiresMode(self) -> Any: ...
    def FixLoopWire(self, aResWires: TopTools_SequenceOfShape) -> bool: ...
    def FixLoopWiresMode(self) -> Any: ...
    def FixMissingSeam(self) -> bool: ...
    def FixMissingSeamMode(self) -> Any: ...
    @overload
    def FixOrientation(self) -> bool: ...
    @overload
    def FixOrientation(self, MapWires: TopTools_DataMapOfShapeListOfShape) -> bool: ...
    def FixOrientationMode(self) -> Any: ...
    def FixPeriodicDegenerated(self) -> bool: ...
    def FixPeriodicDegeneratedMode(self) -> Any: ...
    def FixSmallAreaWire(self, theIsRemoveSmallFace: bool) -> bool: ...
    def FixSmallAreaWireMode(self) -> Any: ...
    def FixSplitFace(self, MapWires: TopTools_DataMapOfShapeListOfShape) -> bool: ...
    def FixSplitFaceMode(self) -> Any: ...
    def FixWireMode(self) -> Any: ...
    def FixWireTool(self) -> ShapeFix_Wire: ...
    def FixWiresTwoCoincEdges(self) -> bool: ...
    @overload
    def Init(self, face: TopoDS_Face) -> None: ...
    @overload
    def Init(self, surf: Geom_Surface, preci: float, fwd: Optional[bool] = True) -> None: ...
    @overload
    def Init(self, surf: ShapeAnalysis_Surface, preci: float, fwd: Optional[bool] = True) -> None: ...
    def Perform(self, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
    def RemoveSmallAreaFaceMode(self) -> Any: ...
    def Result(self) -> TopoDS_Shape: ...
    def SetMaxTolerance(self, maxtol: float) -> None: ...
    def SetMinTolerance(self, mintol: float) -> None: ...
    def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
    def SetPrecision(self, preci: float) -> None: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_FixSmallFace(ShapeFix_Root):
    def __init__(self) -> None: ...
    def ComputeSharedEdgeForStripFace(self, F: TopoDS_Face, E1: TopoDS_Edge, E2: TopoDS_Edge, F1: TopoDS_Face, tol: float) -> TopoDS_Edge: ...
    def FixFace(self, F: TopoDS_Face) -> TopoDS_Face: ...
    def FixPinFace(self, F: TopoDS_Face) -> bool: ...
    def FixShape(self) -> TopoDS_Shape: ...
    def FixSplitFace(self, S: TopoDS_Shape) -> TopoDS_Shape: ...
    def FixSpotFace(self) -> TopoDS_Shape: ...
    def FixStripFace(self, wasdone: Optional[bool] = False) -> TopoDS_Shape: ...
    def Init(self, S: TopoDS_Shape) -> None: ...
    def Perform(self) -> None: ...
    def RemoveFacesInCaseOfSpot(self, F: TopoDS_Face) -> bool: ...
    def RemoveFacesInCaseOfStrip(self, F: TopoDS_Face) -> bool: ...
    def ReplaceInCaseOfStrip(self, F: TopoDS_Face, E1: TopoDS_Edge, E2: TopoDS_Edge, tol: float) -> bool: ...
    def ReplaceVerticesInCaseOfSpot(self, F: TopoDS_Face, tol: float) -> bool: ...
    def Shape(self) -> TopoDS_Shape: ...
    def SplitOneFace(self, F: TopoDS_Face, theSplittedFaces: TopoDS_Compound) -> bool: ...

class ShapeFix_FixSmallSolid(ShapeFix_Root):
    def __init__(self) -> None: ...
    def Merge(self, theShape: TopoDS_Shape, theContext: ShapeBuild_ReShape) -> TopoDS_Shape: ...
    def Remove(self, theShape: TopoDS_Shape, theContext: ShapeBuild_ReShape) -> TopoDS_Shape: ...
    def SetFixMode(self, theMode: int) -> None: ...
    def SetVolumeThreshold(self, theThreshold: Optional[float] = -1.0) -> None: ...
    def SetWidthFactorThreshold(self, theThreshold: Optional[float] = -1.0) -> None: ...

class ShapeFix_Shape(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, shape: TopoDS_Shape) -> None: ...
    def FixEdgeTool(self) -> ShapeFix_Edge: ...
    def FixFaceTool(self) -> ShapeFix_Face: ...
    def FixFreeFaceMode(self) -> Any: ...
    def FixFreeShellMode(self) -> Any: ...
    def FixFreeWireMode(self) -> Any: ...
    def FixSameParameterMode(self) -> Any: ...
    def FixShellTool(self) -> ShapeFix_Shell: ...
    def FixSolidMode(self) -> Any: ...
    def FixSolidTool(self) -> ShapeFix_Solid: ...
    def FixVertexPositionMode(self) -> Any: ...
    def FixVertexTolMode(self) -> Any: ...
    def FixWireTool(self) -> ShapeFix_Wire: ...
    def Init(self, shape: TopoDS_Shape) -> None: ...
    def Perform(self, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
    def SetMaxTolerance(self, maxtol: float) -> None: ...
    def SetMinTolerance(self, mintol: float) -> None: ...
    def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
    def SetPrecision(self, preci: float) -> None: ...
    def Shape(self) -> TopoDS_Shape: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Shell(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, shape: TopoDS_Shell) -> None: ...
    def ErrorFaces(self) -> TopoDS_Compound: ...
    def FixFaceMode(self) -> Any: ...
    def FixFaceOrientation(self, shell: TopoDS_Shell, isAccountMultiConex: Optional[bool] = True, NonManifold: Optional[bool] = False) -> bool: ...
    def FixFaceTool(self) -> ShapeFix_Face: ...
    def FixOrientationMode(self) -> Any: ...
    def Init(self, shell: TopoDS_Shell) -> None: ...
    def NbShells(self) -> int: ...
    def Perform(self, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
    def SetMaxTolerance(self, maxtol: float) -> None: ...
    def SetMinTolerance(self, mintol: float) -> None: ...
    def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
    def SetNonManifoldFlag(self, isNonManifold: bool) -> None: ...
    def SetPrecision(self, preci: float) -> None: ...
    def Shape(self) -> TopoDS_Shape: ...
    def Shell(self) -> TopoDS_Shell: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Solid(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, solid: TopoDS_Solid) -> None: ...
    def CreateOpenSolidMode(self) -> bool: ...
    def FixShellMode(self) -> Any: ...
    def FixShellOrientationMode(self) -> Any: ...
    def FixShellTool(self) -> ShapeFix_Shell: ...
    def Init(self, solid: TopoDS_Solid) -> None: ...
    def Perform(self, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
    def SetMaxTolerance(self, maxtol: float) -> None: ...
    def SetMinTolerance(self, mintol: float) -> None: ...
    def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
    def SetPrecision(self, preci: float) -> None: ...
    def Shape(self) -> TopoDS_Shape: ...
    def Solid(self) -> TopoDS_Shape: ...
    def SolidFromShell(self, shell: TopoDS_Shell) -> TopoDS_Solid: ...
    def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_SplitCommonVertex(ShapeFix_Root):
    def __init__(self) -> None: ...
    def Init(self, S: TopoDS_Shape) -> None: ...
    def Perform(self) -> None: ...
    def Shape(self) -> TopoDS_Shape: ...

class ShapeFix_Wire(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, wire: TopoDS_Wire, face: TopoDS_Face, prec: float) -> None: ...
    def Analyzer(self) -> ShapeAnalysis_Wire: ...
    def ClearModes(self) -> None: ...
    def ClearStatuses(self) -> None: ...
    def ClosedWireMode(self) -> bool: ...
    def Face(self) -> TopoDS_Face: ...
    def FixAddCurve3dMode(self) -> Any: ...
    def FixAddPCurveMode(self) -> Any: ...
    def FixClosed(self, prec: Optional[float] = -1.0) -> bool: ...
    @overload
    def FixConnected(self, prec: Optional[float] = -1.0) -> bool: ...
    @overload
    def FixConnected(self, num: int, prec: float, theUpdateWire: Optional[bool] = True) -> bool: ...
    def FixConnectedMode(self) -> Any: ...
    @overload
    def FixDegenerated(self) -> bool: ...
    @overload
    def FixDegenerated(self, num: int) -> bool: ...
    def FixDegeneratedMode(self) -> Any: ...
    def FixEdgeCurves(self) -> bool: ...
    def FixEdgeCurvesMode(self) -> Any: ...
    def FixEdgeTool(self) -> ShapeFix_Edge: ...
    def FixGap2d(self, num: int, convert: Optional[bool] = False) -> bool: ...
    def FixGap3d(self, num: int, convert: Optional[bool] = False) -> bool: ...
    def FixGaps2d(self) -> bool: ...
    def FixGaps2dMode(self) -> Any: ...
    def FixGaps3d(self) -> bool: ...
    def FixGaps3dMode(self) -> Any: ...
    def FixGapsByRangesMode(self) -> bool: ...
    def FixIntersectingEdgesMode(self) -> Any: ...
    @overload
    def FixLacking(self, force: Optional[bool] = False) -> bool: ...
    @overload
    def FixLacking(self, num: int, force: Optional[bool] = False) -> bool: ...
    def FixLackingMode(self) -> Any: ...
    def FixNonAdjacentIntersectingEdgesMode(self) -> Any: ...
    def FixNotchedEdges(self) -> bool: ...
    def FixNotchedEdgesMode(self) -> Any: ...
    def FixRemoveCurve3dMode(self) -> Any: ...
    def FixRemovePCurveMode(self) -> Any: ...
    @overload
    def FixReorder(self, theModeBoth: Optional[bool] = False) -> bool: ...
    @overload
    def FixReorder(self, wi: ShapeAnalysis_WireOrder) -> bool: ...
    def FixReorderMode(self) -> Any: ...
    def FixReversed2dMode(self) -> Any: ...
    def FixSameParameterMode(self) -> Any: ...
    def FixSeam(self, num: int) -> bool: ...
    def FixSeamMode(self) -> Any: ...
    def FixSelfIntersectingEdgeMode(self) -> Any: ...
    def FixSelfIntersection(self) -> bool: ...
    def FixSelfIntersectionMode(self) -> Any: ...
    def FixShifted(self) -> bool: ...
    def FixShiftedMode(self) -> Any: ...
    @overload
    def FixSmall(self, lockvtx: bool, precsmall: Optional[float] = 0.0) -> int: ...
    @overload
    def FixSmall(self, num: int, lockvtx: bool, precsmall: float) -> bool: ...
    def FixSmallMode(self) -> Any: ...
    def FixTailMode(self) -> Any: ...
    def FixTails(self) -> bool: ...
    def FixVertexToleranceMode(self) -> Any: ...
    @overload
    def Init(self, wire: TopoDS_Wire, face: TopoDS_Face, prec: float) -> None: ...
    @overload
    def Init(self, saw: ShapeAnalysis_Wire) -> None: ...
    def IsLoaded(self) -> bool: ...
    def IsReady(self) -> bool: ...
    def LastFixStatus(self, status: ShapeExtend_Status) -> bool: ...
    @overload
    def Load(self, wire: TopoDS_Wire) -> None: ...
    @overload
    def Load(self, sbwd: ShapeExtend_WireData) -> None: ...
    def ModifyGeometryMode(self) -> bool: ...
    def ModifyRemoveLoopMode(self) -> Any: ...
    def ModifyTopologyMode(self) -> bool: ...
    def NbEdges(self) -> int: ...
    def Perform(self, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
    def PreferencePCurveMode(self) -> bool: ...
    @overload
    def SetFace(self, face: TopoDS_Face) -> None: ...
    @overload
    def SetFace(self, theFace: TopoDS_Face, theSurfaceAnalysis: ShapeAnalysis_Surface) -> None: ...
    def SetMaxTailAngle(self, theMaxTailAngle: float) -> None: ...
    def SetMaxTailWidth(self, theMaxTailWidth: float) -> None: ...
    def SetPrecision(self, prec: float) -> None: ...
    @overload
    def SetSurface(self, theSurfaceAnalysis: ShapeAnalysis_Surface) -> None: ...
    @overload
    def SetSurface(self, surf: Geom_Surface) -> None: ...
    @overload
    def SetSurface(self, surf: Geom_Surface, loc: TopLoc_Location) -> None: ...
    def StatusClosed(self, status: ShapeExtend_Status) -> bool: ...
    def StatusConnected(self, status: ShapeExtend_Status) -> bool: ...
    def StatusDegenerated(self, status: ShapeExtend_Status) -> bool: ...
    def StatusEdgeCurves(self, status: ShapeExtend_Status) -> bool: ...
    def StatusFixTails(self, status: ShapeExtend_Status) -> bool: ...
    def StatusGaps2d(self, status: ShapeExtend_Status) -> bool: ...
    def StatusGaps3d(self, status: ShapeExtend_Status) -> bool: ...
    def StatusLacking(self, status: ShapeExtend_Status) -> bool: ...
    def StatusNotches(self, status: ShapeExtend_Status) -> bool: ...
    def StatusRemovedSegment(self) -> bool: ...
    def StatusReorder(self, status: ShapeExtend_Status) -> bool: ...
    def StatusSelfIntersection(self, status: ShapeExtend_Status) -> bool: ...
    def StatusSmall(self, status: ShapeExtend_Status) -> bool: ...
    def Wire(self) -> TopoDS_Wire: ...
    def WireAPIMake(self) -> TopoDS_Wire: ...
    def WireData(self) -> ShapeExtend_WireData: ...

class ShapeFix_Wireframe(ShapeFix_Root):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, shape: TopoDS_Shape) -> None: ...
    def CheckSmallEdges(self, theSmallEdges: TopTools_MapOfShape, theEdgeToFaces: TopTools_DataMapOfShapeListOfShape, theFaceWithSmall: TopTools_DataMapOfShapeListOfShape, theMultyEdges: TopTools_MapOfShape) -> bool: ...
    def ClearStatuses(self) -> None: ...
    def FixSmallEdges(self) -> bool: ...
    def FixWireGaps(self) -> bool: ...
    def LimitAngle(self) -> float: ...
    def Load(self, shape: TopoDS_Shape) -> None: ...
    def MergeSmallEdges(self, theSmallEdges: TopTools_MapOfShape, theEdgeToFaces: TopTools_DataMapOfShapeListOfShape, theFaceWithSmall: TopTools_DataMapOfShapeListOfShape, theMultyEdges: TopTools_MapOfShape, theModeDrop: Optional[bool] = False, theLimitAngle: Optional[float] = -1) -> bool: ...
    def ModeDropSmallEdges(self) -> bool: ...
    def SetLimitAngle(self, theLimitAngle: float) -> None: ...
    def Shape(self) -> TopoDS_Shape: ...
    def StatusSmallEdges(self, status: ShapeExtend_Status) -> bool: ...
    def StatusWireGaps(self, status: ShapeExtend_Status) -> bool: ...

#classnotwrapped
class ShapeFix_WireSegment: ...

# harray1 classes
# harray2 classes
# hsequence classes

