from enum import IntEnum
from typing import overload, NewType, Optional, Tuple

from OCC.Core.NCollection import *

Standard_Boolean = NewType("Standard_Boolean", bool)
Standard_Byte = NewType("Standard_Byte", uint8_t)
Standard_Character = NewType("Standard_Character", str)
# the following typedef cannot be wrapped as is
Standard_ErrorHandlerCallback = NewType("Standard_ErrorHandlerCallback", Any)
Standard_ExtCharacter = NewType("Standard_ExtCharacter", str)
# the following typedef cannot be wrapped as is
Standard_HMutex = NewType("Standard_HMutex", Any)
# the following typedef cannot be wrapped as is
Standard_IStream = NewType("Standard_IStream", Any)
Standard_Integer = NewType("Standard_Integer", int)
# the following typedef cannot be wrapped as is
Standard_OStream = NewType("Standard_OStream", Any)
Standard_Real = NewType("Standard_Real", float)
# the following typedef cannot be wrapped as is
Standard_SStream = NewType("Standard_SStream", Any)
Standard_ShortReal = NewType("Standard_ShortReal", float)
Standard_Size = NewType("Standard_Size", int)
Standard_ThreadId = NewType("Standard_ThreadId", int)
# the following typedef cannot be wrapped as is
Standard_Time = NewType("Standard_Time", Any)
Standard_UInteger = NewType("Standard_UInteger", int)
Standard_Utf16Char = NewType("Standard_Utf16Char", str)
Standard_Utf32Char = NewType("Standard_Utf32Char", str)
Standard_Utf8Char = NewType("Standard_Utf8Char", str)
Standard_Utf8UChar = NewType("Standard_Utf8UChar", str)
Standard_WideChar = NewType("Standard_WideChar", str)

class standard:
    @staticmethod
    def GetAllocatorType() -> False: ...
    @staticmethod
    def Purge() -> int: ...
    @staticmethod
    def StackTrace(theBuffer: str, theBufferSize: int, theNbTraces: int, theContext: Optional[None] = nullptr, theNbTopSkip: Optional[int] = 0) -> bool: ...

class Standard_ArrayStreamBuffer():
    pass

class Standard_CStringHasher:
    pass

class Standard_Condition:
    def __init__(self, theIsSet: Optional[bool] = false) -> None: ...
    def Check(self) -> bool: ...
    def CheckReset(self) -> bool: ...
    def Reset(self) -> None: ...
    def Set(self) -> None: ...
    @overload
    def Wait(self) -> None: ...
    @overload
    def Wait(self, theTimeMilliseconds: int) -> bool: ...

class Standard_ErrorHandler:
    def __init__(self) -> None: ...
    def Destroy(self) -> None: ...
    def Error(self) -> OSD_SIGBUS,: ...
    @staticmethod
    def IsInTryBlock() -> bool: ...
    def Raise(self) -> None: ...

class Standard_Failure():
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theOther: Standard_Failure) -> None: ...
    @overload
    def __init__(self, theMessage: str) -> None: ...
    @overload
    def __init__(self, theMessage: str, theStackTrace: str) -> None: ...
    @staticmethod
    def DefaultStackTraceLength() -> int: ...
    def ExceptionType(self) -> str: ...
    def GetMessageString(self) -> str: ...
    def GetStackString(self) -> str: ...
    def Print(self) -> str: ...
    @staticmethod
    def SetDefaultStackTraceLength(theNbStackTraces: int) -> None: ...
    def what(self) -> str: ...

class Standard_GUID:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, aGuid: str) -> None: ...
    @overload
    def __init__(self, theUUID: Standard_UUID) -> None: ...
    @overload
    def __init__(self, theGuid: Standard_GUID) -> None: ...
    @overload
    def Assign(self, uid: Standard_GUID) -> None: ...
    @overload
    def Assign(self, uid: Standard_UUID) -> None: ...
    @staticmethod
    def CheckGUIDFormat(aGuid: str) -> bool: ...
    def IsNotSame(self, uid: Standard_GUID) -> bool: ...
    def IsSame(self, uid: Standard_GUID) -> bool: ...
    def ShallowDump(self) -> str: ...
    def ToCString(self, aStrGuid: Standard_PCharacter) -> None: ...
    def ToExtString(self, aStrGuid: Standard_PExtCharacter) -> None: ...
    def ToUUID(self) -> Standard_UUID: ...

class Standard_MMgrRoot:
    def Free(self, thePtr: None) -> None: ...
    def Purge(self, isDestroyed: Optional[bool] = false) -> int: ...

class Standard_Transient:
    @overload
    def __init__(self) -> None: ...
    def DecrementRefCounter(self) -> int: ...
    def Delete(self) -> None: ...
    def DynamicType(self) -> Standard_Type: ...
    def GetRefCount(self) -> int: ...
    def IncrementRefCounter(self) -> None: ...
    @overload
    def IsInstance(self, theType: Standard_Type) -> bool: ...
    @overload
    def IsInstance(self, theTypeName: str) -> bool: ...
    @overload
    def IsKind(self, theType: Standard_Type) -> bool: ...
    @overload
    def IsKind(self, theTypeName: str) -> bool: ...
    def This(self) -> Standard_Transient: ...
    @staticmethod
    def get_type_descriptor() -> Standard_Type: ...
    @staticmethod
    def get_type_name() -> str: ...

class Standard_UUID:
    pass

class Standard_MMgrOpt(Standard_MMgrRoot):
    def Free(self, thePtr: None) -> None: ...
    def Purge(self, isDestroyed: bool) -> int: ...

class Standard_OutOfMemory(Standard_ProgramError):
    def __init__(self, theMessage: Optional[str] = nullptr) -> None: ...
    def ExceptionType(self) -> str: ...
    def SetMessageString(self, theMessage: str) -> None: ...
    def what(self) -> str: ...

class Standard_Persistent(Standard_Transient):
    def __init__(self) -> None: ...
    def TypeNum(self) -> False: ...

class Standard_Type(Standard_Transient):
    def Name(self) -> str: ...
    def Parent(self) -> Standard_Type: ...
    def Print(self) -> str: ...
    def Size(self) -> False: ...
    @overload
    def SubType(self, theOther: Standard_Type) -> bool: ...
    @overload
    def SubType(self, theOther: str) -> bool: ...
    def SystemName(self) -> str: ...

#classnotwrapped
class Standard_AncestorIterator: ...

#classnotwrapped
class Standard_Static_Assert: ...

#classnotwrapped
class Standard_CLocaleSentry: ...

#classnotwrapped
class Standard_Mutex: ...

#classnotwrapped
class Standard_ReadLineBuffer: ...

#classnotwrapped
class Standard_ProgramError: ...

#classnotwrapped
class Standard_ReadBuffer: ...

# harray1 classes
# harray2 classes
# hsequence classes

