from enum import IntEnum
import typing
from typing import Any, overload, NewType, Optional, Tuple

from OCC.Core.Standard import *
from OCC.Core.NCollection import *

Storage_Position = NewType("Storage_Position", long)

class Storage_ArrayOfCallBack:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> typing.Iterator[Any]: ...
    def Init(self, theValue: Any) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDetectable(self) -> bool: ...
    def IsAllocated(self) -> bool: ...
    def First(self) -> Any: ...
    def Last(self) -> Any: ...
    def Value(self, theIndex: int) -> Any: ...
    def SetValue(self, theIndex: int, theValue: Any) -> None: ...

class Storage_SeqOfRoot:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def Size(self) -> int: ...
    def Clear(self) -> None: ...
    def First(self) -> Any: ...
    def Last(self) -> Any: ...
    def Length(self) -> int: ...
    def Append(self, theItem: Any) -> Any: ...
    def Prepend(self, theItem: Any) -> Any: ...
    def RemoveFirst(self) -> None: ...
    def Reverse(self) -> None: ...
    def Value(self, theIndex: int) -> Any: ...
    def SetValue(self, theIndex: int, theValue: Any) -> None: ...

class Storage_MapOfCallBack:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Storage_MapOfPers:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Storage_PType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Storage_Error(IntEnum):
    Storage_VSOk = 0
    Storage_VSOpenError = 1
    Storage_VSModeError = 2
    Storage_VSCloseError = 3
    Storage_VSAlreadyOpen = 4
    Storage_VSNotOpen = 5
    Storage_VSSectionNotFound = 6
    Storage_VSWriteError = 7
    Storage_VSFormatError = 8
    Storage_VSUnknownType = 9
    Storage_VSTypeMismatch = 10
    Storage_VSInternalError = 11
    Storage_VSExtCharParityError = 12
    Storage_VSWrongFileDriver = 13

Storage_VSOk = Storage_Error.Storage_VSOk
Storage_VSOpenError = Storage_Error.Storage_VSOpenError
Storage_VSModeError = Storage_Error.Storage_VSModeError
Storage_VSCloseError = Storage_Error.Storage_VSCloseError
Storage_VSAlreadyOpen = Storage_Error.Storage_VSAlreadyOpen
Storage_VSNotOpen = Storage_Error.Storage_VSNotOpen
Storage_VSSectionNotFound = Storage_Error.Storage_VSSectionNotFound
Storage_VSWriteError = Storage_Error.Storage_VSWriteError
Storage_VSFormatError = Storage_Error.Storage_VSFormatError
Storage_VSUnknownType = Storage_Error.Storage_VSUnknownType
Storage_VSTypeMismatch = Storage_Error.Storage_VSTypeMismatch
Storage_VSInternalError = Storage_Error.Storage_VSInternalError
Storage_VSExtCharParityError = Storage_Error.Storage_VSExtCharParityError
Storage_VSWrongFileDriver = Storage_Error.Storage_VSWrongFileDriver

class Storage_OpenMode(IntEnum):
    Storage_VSNone = 0
    Storage_VSRead = 1
    Storage_VSWrite = 2
    Storage_VSReadWrite = 3

Storage_VSNone = Storage_OpenMode.Storage_VSNone
Storage_VSRead = Storage_OpenMode.Storage_VSRead
Storage_VSWrite = Storage_OpenMode.Storage_VSWrite
Storage_VSReadWrite = Storage_OpenMode.Storage_VSReadWrite

class Storage_SolveMode(IntEnum):
    Storage_AddSolve = 0
    Storage_WriteSolve = 1
    Storage_ReadSolve = 2

Storage_AddSolve = Storage_SolveMode.Storage_AddSolve
Storage_WriteSolve = Storage_SolveMode.Storage_WriteSolve
Storage_ReadSolve = Storage_SolveMode.Storage_ReadSolve

#classnotwrapped
class Storage: ...

#classnotwrapped
class Storage_BaseDriver: ...

#classnotwrapped
class Storage_Bucket: ...

#classnotwrapped
class Storage_BucketOfPersistent: ...

#classnotwrapped
class Storage_BucketIterator: ...

#classnotwrapped
class Storage_CallBack: ...

#classnotwrapped
class Storage_Data: ...

#classnotwrapped
class Storage_DefaultCallBack: ...

#classnotwrapped
class Storage_HeaderData: ...

#classnotwrapped
class Storage_InternalData: ...

#classnotwrapped
class Storage_Root: ...

#classnotwrapped
class Storage_RootData: ...

#classnotwrapped
class Storage_Schema: ...

#classnotwrapped
class Storage_TypeData: ...

#classnotwrapped
class Storage_TypedCallBack: ...

# harray1 classes

class Storage_HArrayOfCallBack(Storage_ArrayOfCallBack, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> Storage_ArrayOfCallBack: ...


class Storage_HArrayOfSchema(Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> Any: ...


class Storage_HPArray(Storage_PArray, Standard_Transient):
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    def Array1(self) -> Storage_PArray: ...

# harray2 classes
# hsequence classes

class Storage_HSeqOfRoot(Storage_SeqOfRoot, Standard_Transient):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: Storage_SeqOfRoot) -> None: ...
    def Sequence(self) -> Storage_SeqOfRoot: ...
    def Append(self, theSequence: Storage_SeqOfRoot) -> None: ...


