from typing import NewType, Optional, Tuple

from OCC.Core.XCAFDimTolObjects import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TopoDS import *
from OCC.Core.gp import *
from OCC.Core.TCollection import *
from OCC.Core.TColStd import *
from OCC.Core.TDocStd import *


class XCAFDimTolObjects_GeomToleranceType:
	XCAFDimTolObjects_GeomToleranceType_None: int = ...
	XCAFDimTolObjects_GeomToleranceType_Angularity: int = ...
	XCAFDimTolObjects_GeomToleranceType_CircularRunout: int = ...
	XCAFDimTolObjects_GeomToleranceType_CircularityOrRoundness: int = ...
	XCAFDimTolObjects_GeomToleranceType_Coaxiality: int = ...
	XCAFDimTolObjects_GeomToleranceType_Concentricity: int = ...
	XCAFDimTolObjects_GeomToleranceType_Cylindricity: int = ...
	XCAFDimTolObjects_GeomToleranceType_Flatness: int = ...
	XCAFDimTolObjects_GeomToleranceType_Parallelism: int = ...
	XCAFDimTolObjects_GeomToleranceType_Perpendicularity: int = ...
	XCAFDimTolObjects_GeomToleranceType_Position: int = ...
	XCAFDimTolObjects_GeomToleranceType_ProfileOfLine: int = ...
	XCAFDimTolObjects_GeomToleranceType_ProfileOfSurface: int = ...
	XCAFDimTolObjects_GeomToleranceType_Straightness: int = ...
	XCAFDimTolObjects_GeomToleranceType_Symmetry: int = ...
	XCAFDimTolObjects_GeomToleranceType_TotalRunout: int = ...

class XCAFDimTolObjects_GeomToleranceModif:
	XCAFDimTolObjects_GeomToleranceModif_Any_Cross_Section: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Common_Zone: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Each_Radial_Element: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Free_State: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Least_Material_Requirement: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Line_Element: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Major_Diameter: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Maximum_Material_Requirement: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Minor_Diameter: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Not_Convex: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Pitch_Diameter: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Reciprocity_Requirement: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Separate_Requirement: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Statistical_Tolerance: int = ...
	XCAFDimTolObjects_GeomToleranceModif_Tangent_Plane: int = ...
	XCAFDimTolObjects_GeomToleranceModif_All_Around: int = ...
	XCAFDimTolObjects_GeomToleranceModif_All_Over: int = ...

class XCAFDimTolObjects_DimensionModif:
	XCAFDimTolObjects_DimensionModif_ControlledRadius: int = ...
	XCAFDimTolObjects_DimensionModif_Square: int = ...
	XCAFDimTolObjects_DimensionModif_StatisticalTolerance: int = ...
	XCAFDimTolObjects_DimensionModif_ContinuousFeature: int = ...
	XCAFDimTolObjects_DimensionModif_TwoPointSize: int = ...
	XCAFDimTolObjects_DimensionModif_LocalSizeDefinedBySphere: int = ...
	XCAFDimTolObjects_DimensionModif_LeastSquaresAssociationCriterion: int = ...
	XCAFDimTolObjects_DimensionModif_MaximumInscribedAssociation: int = ...
	XCAFDimTolObjects_DimensionModif_MinimumCircumscribedAssociation: int = ...
	XCAFDimTolObjects_DimensionModif_CircumferenceDiameter: int = ...
	XCAFDimTolObjects_DimensionModif_AreaDiameter: int = ...
	XCAFDimTolObjects_DimensionModif_VolumeDiameter: int = ...
	XCAFDimTolObjects_DimensionModif_MaximumSize: int = ...
	XCAFDimTolObjects_DimensionModif_MinimumSize: int = ...
	XCAFDimTolObjects_DimensionModif_AverageSize: int = ...
	XCAFDimTolObjects_DimensionModif_MedianSize: int = ...
	XCAFDimTolObjects_DimensionModif_MidRangeSize: int = ...
	XCAFDimTolObjects_DimensionModif_RangeOfSizes: int = ...
	XCAFDimTolObjects_DimensionModif_AnyRestrictedPortionOfFeature: int = ...
	XCAFDimTolObjects_DimensionModif_AnyCrossSection: int = ...
	XCAFDimTolObjects_DimensionModif_SpecificFixedCrossSection: int = ...
	XCAFDimTolObjects_DimensionModif_CommonTolerance: int = ...
	XCAFDimTolObjects_DimensionModif_FreeStateCondition: int = ...
	XCAFDimTolObjects_DimensionModif_Between: int = ...

class XCAFDimTolObjects_DatumModifWithValue:
	XCAFDimTolObjects_DatumModifWithValue_None: int = ...
	XCAFDimTolObjects_DatumModifWithValue_CircularOrCylindrical: int = ...
	XCAFDimTolObjects_DatumModifWithValue_Distance: int = ...
	XCAFDimTolObjects_DatumModifWithValue_Projected: int = ...
	XCAFDimTolObjects_DatumModifWithValue_Spherical: int = ...

class XCAFDimTolObjects_DimensionFormVariance:
	XCAFDimTolObjects_DimensionFormVariance_None: int = ...
	XCAFDimTolObjects_DimensionFormVariance_A: int = ...
	XCAFDimTolObjects_DimensionFormVariance_B: int = ...
	XCAFDimTolObjects_DimensionFormVariance_C: int = ...
	XCAFDimTolObjects_DimensionFormVariance_CD: int = ...
	XCAFDimTolObjects_DimensionFormVariance_D: int = ...
	XCAFDimTolObjects_DimensionFormVariance_E: int = ...
	XCAFDimTolObjects_DimensionFormVariance_EF: int = ...
	XCAFDimTolObjects_DimensionFormVariance_F: int = ...
	XCAFDimTolObjects_DimensionFormVariance_FG: int = ...
	XCAFDimTolObjects_DimensionFormVariance_G: int = ...
	XCAFDimTolObjects_DimensionFormVariance_H: int = ...
	XCAFDimTolObjects_DimensionFormVariance_JS: int = ...
	XCAFDimTolObjects_DimensionFormVariance_J: int = ...
	XCAFDimTolObjects_DimensionFormVariance_K: int = ...
	XCAFDimTolObjects_DimensionFormVariance_M: int = ...
	XCAFDimTolObjects_DimensionFormVariance_N: int = ...
	XCAFDimTolObjects_DimensionFormVariance_P: int = ...
	XCAFDimTolObjects_DimensionFormVariance_R: int = ...
	XCAFDimTolObjects_DimensionFormVariance_S: int = ...
	XCAFDimTolObjects_DimensionFormVariance_T: int = ...
	XCAFDimTolObjects_DimensionFormVariance_U: int = ...
	XCAFDimTolObjects_DimensionFormVariance_V: int = ...
	XCAFDimTolObjects_DimensionFormVariance_X: int = ...
	XCAFDimTolObjects_DimensionFormVariance_Y: int = ...
	XCAFDimTolObjects_DimensionFormVariance_Z: int = ...
	XCAFDimTolObjects_DimensionFormVariance_ZA: int = ...
	XCAFDimTolObjects_DimensionFormVariance_ZB: int = ...
	XCAFDimTolObjects_DimensionFormVariance_ZC: int = ...

class XCAFDimTolObjects_GeomToleranceZoneModif:
	XCAFDimTolObjects_GeomToleranceZoneModif_None: int = ...
	XCAFDimTolObjects_GeomToleranceZoneModif_Projected: int = ...
	XCAFDimTolObjects_GeomToleranceZoneModif_Runout: int = ...
	XCAFDimTolObjects_GeomToleranceZoneModif_NonUniform: int = ...

class XCAFDimTolObjects_DatumTargetType:
	XCAFDimTolObjects_DatumTargetType_Point: int = ...
	XCAFDimTolObjects_DatumTargetType_Line: int = ...
	XCAFDimTolObjects_DatumTargetType_Rectangle: int = ...
	XCAFDimTolObjects_DatumTargetType_Circle: int = ...
	XCAFDimTolObjects_DatumTargetType_Area: int = ...

class XCAFDimTolObjects_DatumSingleModif:
	XCAFDimTolObjects_DatumSingleModif_AnyCrossSection: int = ...
	XCAFDimTolObjects_DatumSingleModif_Any_LongitudinalSection: int = ...
	XCAFDimTolObjects_DatumSingleModif_Basic: int = ...
	XCAFDimTolObjects_DatumSingleModif_ContactingFeature: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintU: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintV: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintW: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintX: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintY: int = ...
	XCAFDimTolObjects_DatumSingleModif_DegreeOfFreedomConstraintZ: int = ...
	XCAFDimTolObjects_DatumSingleModif_DistanceVariable: int = ...
	XCAFDimTolObjects_DatumSingleModif_FreeState: int = ...
	XCAFDimTolObjects_DatumSingleModif_LeastMaterialRequirement: int = ...
	XCAFDimTolObjects_DatumSingleModif_Line: int = ...
	XCAFDimTolObjects_DatumSingleModif_MajorDiameter: int = ...
	XCAFDimTolObjects_DatumSingleModif_MaximumMaterialRequirement: int = ...
	XCAFDimTolObjects_DatumSingleModif_MinorDiameter: int = ...
	XCAFDimTolObjects_DatumSingleModif_Orientation: int = ...
	XCAFDimTolObjects_DatumSingleModif_PitchDiameter: int = ...
	XCAFDimTolObjects_DatumSingleModif_Plane: int = ...
	XCAFDimTolObjects_DatumSingleModif_Point: int = ...
	XCAFDimTolObjects_DatumSingleModif_Translation: int = ...

class XCAFDimTolObjects_DimensionQualifier:
	XCAFDimTolObjects_DimensionQualifier_None: int = ...
	XCAFDimTolObjects_DimensionQualifier_Min: int = ...
	XCAFDimTolObjects_DimensionQualifier_Max: int = ...
	XCAFDimTolObjects_DimensionQualifier_Avg: int = ...

class XCAFDimTolObjects_GeomToleranceTypeValue:
	XCAFDimTolObjects_GeomToleranceTypeValue_None: int = ...
	XCAFDimTolObjects_GeomToleranceTypeValue_Diameter: int = ...
	XCAFDimTolObjects_GeomToleranceTypeValue_SphericalDiameter: int = ...

class XCAFDimTolObjects_ToleranceZoneAffectedPlane:
	XCAFDimTolObjects_ToleranceZoneAffectedPlane_None: int = ...
	XCAFDimTolObjects_ToleranceZoneAffectedPlane_Intersection: int = ...
	XCAFDimTolObjects_ToleranceZoneAffectedPlane_Orientation: int = ...

class XCAFDimTolObjects_DimensionType:
	XCAFDimTolObjects_DimensionType_Location_None: int = ...
	XCAFDimTolObjects_DimensionType_Location_CurvedDistance: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToOuter: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToInner: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToCenter: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToOuter: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToInner: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToCenter: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToOuter: int = ...
	XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToInner: int = ...
	XCAFDimTolObjects_DimensionType_Location_Angular: int = ...
	XCAFDimTolObjects_DimensionType_Location_Oriented: int = ...
	XCAFDimTolObjects_DimensionType_Location_WithPath: int = ...
	XCAFDimTolObjects_DimensionType_Size_CurveLength: int = ...
	XCAFDimTolObjects_DimensionType_Size_Diameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_SphericalDiameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_Radius: int = ...
	XCAFDimTolObjects_DimensionType_Size_SphericalRadius: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalMinorDiameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalMajorDiameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalMinorRadius: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalMajorRadius: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorDiameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorDiameter: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorRadius: int = ...
	XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorRadius: int = ...
	XCAFDimTolObjects_DimensionType_Size_Thickness: int = ...
	XCAFDimTolObjects_DimensionType_Size_Angular: int = ...
	XCAFDimTolObjects_DimensionType_Size_WithPath: int = ...
	XCAFDimTolObjects_DimensionType_CommonLabel: int = ...
	XCAFDimTolObjects_DimensionType_DimensionPresentation: int = ...

class XCAFDimTolObjects_GeomToleranceMatReqModif:
	XCAFDimTolObjects_GeomToleranceMatReqModif_None: int = ...
	XCAFDimTolObjects_GeomToleranceMatReqModif_M: int = ...
	XCAFDimTolObjects_GeomToleranceMatReqModif_L: int = ...

class XCAFDimTolObjects_DimensionGrade:
	XCAFDimTolObjects_DimensionGrade_IT01: int = ...
	XCAFDimTolObjects_DimensionGrade_IT0: int = ...
	XCAFDimTolObjects_DimensionGrade_IT1: int = ...
	XCAFDimTolObjects_DimensionGrade_IT2: int = ...
	XCAFDimTolObjects_DimensionGrade_IT3: int = ...
	XCAFDimTolObjects_DimensionGrade_IT4: int = ...
	XCAFDimTolObjects_DimensionGrade_IT5: int = ...
	XCAFDimTolObjects_DimensionGrade_IT6: int = ...
	XCAFDimTolObjects_DimensionGrade_IT7: int = ...
	XCAFDimTolObjects_DimensionGrade_IT8: int = ...
	XCAFDimTolObjects_DimensionGrade_IT9: int = ...
	XCAFDimTolObjects_DimensionGrade_IT10: int = ...
	XCAFDimTolObjects_DimensionGrade_IT11: int = ...
	XCAFDimTolObjects_DimensionGrade_IT12: int = ...
	XCAFDimTolObjects_DimensionGrade_IT13: int = ...
	XCAFDimTolObjects_DimensionGrade_IT14: int = ...
	XCAFDimTolObjects_DimensionGrade_IT15: int = ...
	XCAFDimTolObjects_DimensionGrade_IT16: int = ...
	XCAFDimTolObjects_DimensionGrade_IT17: int = ...
	XCAFDimTolObjects_DimensionGrade_IT18: int = ...

class XCAFDimTolObjects_DatumObject(Standard_Transient):
	def __init__(self) -> None: ...
	def __init__(self, theObj: XCAFDimTolObjects_DatumObject) -> None: ...
	def AddModifier(self, theModifier: XCAFDimTolObjects_DatumSingleModif) -> None: ...
	def GetDatumTarget(self) -> TopoDS_Shape: ...
	def GetDatumTargetAxis(self) -> gp_Ax2: ...
	def GetDatumTargetLength(self) -> float: ...
	def GetDatumTargetNumber(self) -> int: ...
	def GetDatumTargetType(self) -> XCAFDimTolObjects_DatumTargetType: ...
	def GetDatumTargetWidth(self) -> float: ...
	def GetModifierWithValue(self, theModifier: XCAFDimTolObjects_DatumModifWithValue) -> float: ...
	def GetModifiers(self) -> XCAFDimTolObjects_DatumModifiersSequence: ...
	def GetName(self) -> TCollection_HAsciiString: ...
	def GetPlane(self) -> gp_Ax2: ...
	def GetPoint(self) -> gp_Pnt: ...
	def GetPointTextAttach(self) -> gp_Pnt: ...
	def GetPosition(self) -> int: ...
	def GetPresentation(self) -> TopoDS_Shape: ...
	def GetPresentationName(self) -> TCollection_HAsciiString: ...
	def GetSemanticName(self) -> TCollection_HAsciiString: ...
	def HasDatumTargetParams(self) -> bool: ...
	def HasPlane(self) -> bool: ...
	def HasPoint(self) -> bool: ...
	def HasPointText(self) -> bool: ...
	def IsDatumTarget(self) -> bool: ...
	def IsDatumTarget(self, theIsDT: bool) -> None: ...
	def SetDatumTarget(self, theShape: TopoDS_Shape) -> None: ...
	def SetDatumTargetAxis(self, theAxis: gp_Ax2) -> None: ...
	def SetDatumTargetLength(self, theLength: float) -> None: ...
	def SetDatumTargetNumber(self, theNumber: int) -> None: ...
	def SetDatumTargetType(self, theType: XCAFDimTolObjects_DatumTargetType) -> None: ...
	def SetDatumTargetWidth(self, theWidth: float) -> None: ...
	def SetModifierWithValue(self, theModifier: XCAFDimTolObjects_DatumModifWithValue, theValue: float) -> None: ...
	def SetModifiers(self, theModifiers: XCAFDimTolObjects_DatumModifiersSequence) -> None: ...
	def SetName(self, theTag: TCollection_HAsciiString) -> None: ...
	def SetPlane(self, thePlane: gp_Ax2) -> None: ...
	def SetPoint(self, thePnt: gp_Pnt) -> None: ...
	def SetPointTextAttach(self, thePntText: gp_Pnt) -> None: ...
	def SetPosition(self, thePosition: int) -> None: ...
	def SetPresentation(self, thePresentation: TopoDS_Shape, thePresentationName: TCollection_HAsciiString) -> None: ...
	def SetSemanticName(self, theName: TCollection_HAsciiString) -> None: ...

class XCAFDimTolObjects_DimensionObject(Standard_Transient):
	def __init__(self) -> None: ...
	def __init__(self, theObj: XCAFDimTolObjects_DimensionObject) -> None: ...
	def AddDescription(self, theDescription: TCollection_HAsciiString, theName: TCollection_HAsciiString) -> None: ...
	def AddModifier(self, theModifier: XCAFDimTolObjects_DimensionModif) -> None: ...
	def GetClassOfTolerance(self, theFormVariance: XCAFDimTolObjects_DimensionFormVariance, theGrade: XCAFDimTolObjects_DimensionGrade) -> Tuple[bool, bool]: ...
	def GetDescription(self, theNumber: int) -> TCollection_HAsciiString: ...
	def GetDescriptionName(self, theNumber: int) -> TCollection_HAsciiString: ...
	def GetDirection(self, theDir: gp_Dir) -> bool: ...
	def GetLowerBound(self) -> float: ...
	def GetLowerTolValue(self) -> float: ...
	def GetModifiers(self) -> XCAFDimTolObjects_DimensionModifiersSequence: ...
	def GetNbOfDecimalPlaces(self) -> Tuple[int, int]: ...
	def GetPath(self) -> TopoDS_Edge: ...
	def GetPlane(self) -> gp_Ax2: ...
	def GetPoint(self) -> gp_Pnt: ...
	def GetPoint2(self) -> gp_Pnt: ...
	def GetPointTextAttach(self) -> gp_Pnt: ...
	def GetPresentation(self) -> TopoDS_Shape: ...
	def GetPresentationName(self) -> TCollection_HAsciiString: ...
	def GetQualifier(self) -> XCAFDimTolObjects_DimensionQualifier: ...
	def GetSemanticName(self) -> TCollection_HAsciiString: ...
	def GetType(self) -> XCAFDimTolObjects_DimensionType: ...
	def GetUpperBound(self) -> float: ...
	def GetUpperTolValue(self) -> float: ...
	def GetValue(self) -> float: ...
	def GetValues(self) -> TColStd_HArray1OfReal: ...
	def HasDescriptions(self) -> bool: ...
	def HasPlane(self) -> bool: ...
	def HasPoint(self) -> bool: ...
	def HasPoint2(self) -> bool: ...
	def HasQualifier(self) -> bool: ...
	def HasTextPoint(self) -> bool: ...
	def IsDimWithClassOfTolerance(self) -> bool: ...
	def IsDimWithPlusMinusTolerance(self) -> bool: ...
	def IsDimWithRange(self) -> bool: ...
	def NbDescriptions(self) -> int: ...
	def RemoveDescription(self, theNumber: int) -> None: ...
	def SetClassOfTolerance(self, theHole: bool, theFormVariance: XCAFDimTolObjects_DimensionFormVariance, theGrade: XCAFDimTolObjects_DimensionGrade) -> None: ...
	def SetDirection(self, theDir: gp_Dir) -> bool: ...
	def SetLowerBound(self, theLowerBound: float) -> None: ...
	def SetLowerTolValue(self, theLowerTolValue: float) -> bool: ...
	def SetModifiers(self, theModifiers: XCAFDimTolObjects_DimensionModifiersSequence) -> None: ...
	def SetNbOfDecimalPlaces(self, theL: int, theR: int) -> None: ...
	def SetPath(self, thePath: TopoDS_Edge) -> None: ...
	def SetPlane(self, thePlane: gp_Ax2) -> None: ...
	def SetPoint(self, thePnt: gp_Pnt) -> None: ...
	def SetPoint2(self, thePnt: gp_Pnt) -> None: ...
	def SetPointTextAttach(self, thePntText: gp_Pnt) -> None: ...
	def SetPresentation(self, thePresentation: TopoDS_Shape, thePresentationName: TCollection_HAsciiString) -> None: ...
	def SetQualifier(self, theQualifier: XCAFDimTolObjects_DimensionQualifier) -> None: ...
	def SetSemanticName(self, theName: TCollection_HAsciiString) -> None: ...
	def SetType(self, theTyupe: XCAFDimTolObjects_DimensionType) -> None: ...
	def SetUpperBound(self, theUpperBound: float) -> None: ...
	def SetUpperTolValue(self, theUperTolValue: float) -> bool: ...
	def SetValue(self, theValue: float) -> None: ...
	def SetValues(self, theValue: TColStd_HArray1OfReal) -> None: ...

class XCAFDimTolObjects_GeomToleranceObject(Standard_Transient):
	def __init__(self) -> None: ...
	def __init__(self, theObj: XCAFDimTolObjects_GeomToleranceObject) -> None: ...
	def AddModifier(self, theModifier: XCAFDimTolObjects_GeomToleranceModif) -> None: ...
	def GetAffectedPlane(self) -> gp_Pln: ...
	def GetAffectedPlaneType(self) -> XCAFDimTolObjects_ToleranceZoneAffectedPlane: ...
	def GetAxis(self) -> gp_Ax2: ...
	def GetMaterialRequirementModifier(self) -> XCAFDimTolObjects_GeomToleranceMatReqModif: ...
	def GetMaxValueModifier(self) -> float: ...
	def GetModifiers(self) -> XCAFDimTolObjects_GeomToleranceModifiersSequence: ...
	def GetPlane(self) -> gp_Ax2: ...
	def GetPoint(self) -> gp_Pnt: ...
	def GetPointTextAttach(self) -> gp_Pnt: ...
	def GetPresentation(self) -> TopoDS_Shape: ...
	def GetPresentationName(self) -> TCollection_HAsciiString: ...
	def GetSemanticName(self) -> TCollection_HAsciiString: ...
	def GetType(self) -> XCAFDimTolObjects_GeomToleranceType: ...
	def GetTypeOfValue(self) -> XCAFDimTolObjects_GeomToleranceTypeValue: ...
	def GetValue(self) -> float: ...
	def GetValueOfZoneModifier(self) -> float: ...
	def GetZoneModifier(self) -> XCAFDimTolObjects_GeomToleranceZoneModif: ...
	def HasAffectedPlane(self) -> False: ...
	def HasAxis(self) -> bool: ...
	def HasPlane(self) -> bool: ...
	def HasPoint(self) -> bool: ...
	def HasPointText(self) -> bool: ...
	def SetAffectedPlane(self, thePlane: gp_Pln) -> None: ...
	def SetAffectedPlane(self, thePlane: gp_Pln, theType: XCAFDimTolObjects_ToleranceZoneAffectedPlane) -> None: ...
	def SetAffectedPlaneType(self, theType: XCAFDimTolObjects_ToleranceZoneAffectedPlane) -> None: ...
	def SetAxis(self, theAxis: gp_Ax2) -> None: ...
	def SetMaterialRequirementModifier(self, theMatReqModif: XCAFDimTolObjects_GeomToleranceMatReqModif) -> None: ...
	def SetMaxValueModifier(self, theModifier: float) -> None: ...
	def SetModifiers(self, theModifiers: XCAFDimTolObjects_GeomToleranceModifiersSequence) -> None: ...
	def SetPlane(self, thePlane: gp_Ax2) -> None: ...
	def SetPoint(self, thePnt: gp_Pnt) -> None: ...
	def SetPointTextAttach(self, thePntText: gp_Pnt) -> None: ...
	def SetPresentation(self, thePresentation: TopoDS_Shape, thePresentationName: TCollection_HAsciiString) -> None: ...
	def SetSemanticName(self, theName: TCollection_HAsciiString) -> None: ...
	def SetType(self, theType: XCAFDimTolObjects_GeomToleranceType) -> None: ...
	def SetTypeOfValue(self, theTypeOfValue: XCAFDimTolObjects_GeomToleranceTypeValue) -> None: ...
	def SetValue(self, theValue: float) -> None: ...
	def SetValueOfZoneModifier(self, theValue: float) -> None: ...
	def SetZoneModifier(self, theZoneModif: XCAFDimTolObjects_GeomToleranceZoneModif) -> None: ...

class XCAFDimTolObjects_Tool:
	def __init__(self, theDoc: TDocStd_Document) -> None: ...
	def GetDimensions(self, theDimensionObjectSequence: XCAFDimTolObjects_DimensionObjectSequence) -> None: ...
	def GetGeomTolerances(self, theGeomToleranceObjectSequence: XCAFDimTolObjects_GeomToleranceObjectSequence, theDatumObjectSequence: XCAFDimTolObjects_DatumObjectSequence, theMap: XCAFDimTolObjects_DataMapOfToleranceDatum) -> None: ...
	def GetRefDatum(self, theShape: TopoDS_Shape, theDatum: XCAFDimTolObjects_DatumObject) -> bool: ...
	def GetRefDimensions(self, theShape: TopoDS_Shape, theDimensions: XCAFDimTolObjects_DimensionObjectSequence) -> bool: ...
	def GetRefGeomTolerances(self, theShape: TopoDS_Shape, theGeomToleranceObjectSequence: XCAFDimTolObjects_GeomToleranceObjectSequence, theDatumObjectSequence: XCAFDimTolObjects_DatumObjectSequence, theMap: XCAFDimTolObjects_DataMapOfToleranceDatum) -> bool: ...
