from typing import NewType, Optional, Tuple

from OCC.Core.XmlLDrivers import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.Message import *
from OCC.Core.XmlMDF import *
from OCC.Core.TCollection import *
from OCC.Core.TDocStd import *
from OCC.Core.PCDM import *
from OCC.Core.CDM import *
from OCC.Core.Storage import *


class XmlLDrivers:
	@staticmethod
	def AttributeDrivers(self, theMsgDriver: Message_Messenger) -> XmlMDF_ADriverTable: ...
	@staticmethod
	def CreationDate(self) -> TCollection_AsciiString: ...
	@staticmethod
	def DefineFormat(self, theApp: TDocStd_Application) -> None: ...
	@staticmethod
	def Factory(self, theGUID: Standard_GUID) -> Standard_Transient: ...
	@staticmethod
	def StorageVersion(self) -> int: ...

class XmlLDrivers_DocumentRetrievalDriver(PCDM_RetrievalDriver):
	def __init__(self) -> None: ...
	def AttributeDrivers(self, theMsgDriver: Message_Messenger) -> XmlMDF_ADriverTable: ...
	def CreateDocument(self) -> CDM_Document: ...
	def Read(self, theFileName: TCollection_ExtendedString, theNewDocument: CDM_Document, theApplication: CDM_Application) -> None: ...

class XmlLDrivers_DocumentStorageDriver(PCDM_StorageDriver):
	def __init__(self, theCopyright: TCollection_ExtendedString) -> None: ...
	def AttributeDrivers(self, theMsgDriver: Message_Messenger) -> XmlMDF_ADriverTable: ...
	def Write(self, theDocument: CDM_Document, theFileName: TCollection_ExtendedString) -> None: ...

class XmlLDrivers_NamespaceDef:
	def __init__(self) -> None: ...
	def __init__(self, thePrefix: TCollection_AsciiString, theURI: TCollection_AsciiString) -> None: ...
	def Prefix(self) -> TCollection_AsciiString: ...
	def URI(self) -> TCollection_AsciiString: ...
